// Auto-generated file - do not edit manually
// This file is generated by build.ts

import provider_0 from "./lib/aihot.json" with { type: "json" }
import provider_1 from "./lib/browser"
import provider_2 from "./lib/cls"
import provider_3 from "./lib/github.json" with { type: "json" }
import provider_4 from "./lib/hackernews.json" with { type: "json" }
import provider_5 from "./lib/linuxdo.json" with { type: "json" }
import provider_6 from "./lib/netease-music.json" with { type: "json" }
import provider_7 from "./lib/newsnow.json" with { type: "json" }
import provider_8 from "./lib/telegram.json" with { type: "json" }
import provider_9 from "./lib/tieba.json" with { type: "json" }
import provider_10 from "./lib/v2ex.json" with { type: "json" }
import provider_11 from "./lib/xueqiu.json" with { type: "json" }
import provider_12 from "./lib/zhihu.json" with { type: "json" }
import type { ProviderConfig } from "./utils/source"
import { resolveProvider } from "./utils/source"

export const providers = {
  "aihot": resolveProvider("aihot", provider_0 as ProviderConfig),
  "browser": resolveProvider("browser", provider_1),
  "cls": resolveProvider("cls", provider_2),
  "github": resolveProvider("github", provider_3 as ProviderConfig),
  "hackernews": resolveProvider("hackernews", provider_4 as ProviderConfig),
  "linuxdo": resolveProvider("linuxdo", provider_5 as ProviderConfig),
  "netease-music": resolveProvider("netease-music", provider_6 as ProviderConfig),
  "newsnow": resolveProvider("newsnow", provider_7 as ProviderConfig),
  "telegram": resolveProvider("telegram", provider_8 as ProviderConfig),
  "tieba": resolveProvider("tieba", provider_9 as ProviderConfig),
  "v2ex": resolveProvider("v2ex", provider_10 as ProviderConfig),
  "xueqiu": resolveProvider("xueqiu", provider_11 as ProviderConfig),
  "zhihu": resolveProvider("zhihu", provider_12 as ProviderConfig)
}
