// Auto-generated file - do not edit manually
// This file is generated by build.ts

import provider_0 from "./lib/bilibili"
import provider_1 from "./lib/browser"
import provider_2 from "./lib/cls"
import provider_3 from "./lib/folo"
import provider_4 from "./lib/jike/index"
import provider_5 from "./lib/weibo/index"
import provider_6 from "./lib/x/index"
import { resolveProvider } from "./utils/source"

export const providers = {
  "bilibili": resolveProvider("bilibili", provider_0),
  "browser": resolveProvider("browser", provider_1),
  "cls": resolveProvider("cls", provider_2),
  "folo": resolveProvider("folo", provider_3),
  "jike": resolveProvider("jike", provider_4),
  "weibo": resolveProvider("weibo", provider_5),
  "x": resolveProvider("x", provider_6)
}
