// Auto-generated file - do not edit manually
// This file is generated by build.ts

import provider_0 from "./lib/aihot.json" with { type: "json" }
import provider_1 from "./lib/bilibili"
import provider_2 from "./lib/browser"
import provider_3 from "./lib/cls"
import provider_4 from "./lib/folo"
import provider_5 from "./lib/github.json" with { type: "json" }
import provider_6 from "./lib/hackernews.json" with { type: "json" }
import provider_7 from "./lib/jike/index"
import provider_8 from "./lib/linuxdo.json" with { type: "json" }
import provider_9 from "./lib/netease-music.json" with { type: "json" }
import provider_10 from "./lib/newsnow.json" with { type: "json" }
import provider_11 from "./lib/telegram.json" with { type: "json" }
import provider_12 from "./lib/tieba.json" with { type: "json" }
import provider_13 from "./lib/v2ex.json" with { type: "json" }
import provider_14 from "./lib/weibo/index"
import provider_15 from "./lib/x/index"
import provider_16 from "./lib/xueqiu.json" with { type: "json" }
import provider_17 from "./lib/zaobao.json" with { type: "json" }
import provider_18 from "./lib/zhihu.json" with { type: "json" }
import type { ProviderConfig } from "./utils/source"
import { resolveProvider } from "./utils/source"

export const providers = {
  "aihot": resolveProvider("aihot", provider_0 as ProviderConfig),
  "bilibili": resolveProvider("bilibili", provider_1),
  "browser": resolveProvider("browser", provider_2),
  "cls": resolveProvider("cls", provider_3),
  "folo": resolveProvider("folo", provider_4),
  "github": resolveProvider("github", provider_5 as ProviderConfig),
  "hackernews": resolveProvider("hackernews", provider_6 as ProviderConfig),
  "jike": resolveProvider("jike", provider_7),
  "linuxdo": resolveProvider("linuxdo", provider_8 as ProviderConfig),
  "netease-music": resolveProvider("netease-music", provider_9 as ProviderConfig),
  "newsnow": resolveProvider("newsnow", provider_10 as ProviderConfig),
  "telegram": resolveProvider("telegram", provider_11 as ProviderConfig),
  "tieba": resolveProvider("tieba", provider_12 as ProviderConfig),
  "v2ex": resolveProvider("v2ex", provider_13 as ProviderConfig),
  "weibo": resolveProvider("weibo", provider_14),
  "x": resolveProvider("x", provider_15),
  "xueqiu": resolveProvider("xueqiu", provider_16 as ProviderConfig),
  "zaobao": resolveProvider("zaobao", provider_17 as ProviderConfig),
  "zhihu": resolveProvider("zhihu", provider_18 as ProviderConfig)
}
