// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "@newsnext/source/typings"

export const sourceDescriptors: SourceDescriptor[] = [
  {
    "icon": "https://icons.folo.is/aihot.virxact.com",
    "providerTitle": "AIHot",
    "capabilities": {
      "network": [
        "aihot.virxact.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "blue",
    "type": "timeline",
    "category": "tech",
    "home": "https://aihot.virxact.com",
    "id": "aihot:all"
  },
  {
    "icon": "https://www.google.com/chrome/static/images/favicons/favicon-96x96.png",
    "providerTitle": "Browser",
    "title": "History",
    "params": {
      "query": {
        "type": "text",
        "title": "Search",
        "default": ""
      },
      "dateRange": {
        "type": "select",
        "title": "Date range",
        "values": [
          {
            "label": "Today",
            "value": "today"
          },
          {
            "label": "Last 7 days",
            "value": "week"
          },
          {
            "label": "Last 30 days",
            "value": "month"
          },
          {
            "label": "All history",
            "value": "all"
          }
        ],
        "default": "week"
      },
      "maxResults": {
        "type": "number",
        "title": "Limit",
        "default": 50,
        "min": 1,
        "max": 100
      }
    },
    "capabilities": {
      "network": [],
      "cookies": [],
      "browser": [
        "history"
      ]
    },
    "cache": {
      "version": 1,
      "maxAge": "1m"
    },
    "color": "blue",
    "type": "timeline",
    "category": "others",
    "id": "browser:history"
  },
  {
    "icon": "https://www.google.com/chrome/static/images/favicons/favicon-96x96.png",
    "providerTitle": "Browser",
    "title": "Bookmarks",
    "params": {
      "folder": {
        "type": "text",
        "title": "Folder",
        "description": "Leave empty to include every bookmark. Use a folder ID, title, or path.",
        "default": ""
      },
      "maxResults": {
        "type": "number",
        "title": "Limit",
        "default": 50,
        "min": 1,
        "max": 200
      }
    },
    "capabilities": {
      "network": [],
      "cookies": [],
      "browser": [
        "bookmarks",
        "favicon"
      ]
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "blue",
    "type": "timeline",
    "category": "others",
    "id": "browser:bookmarks"
  },
  {
    "icon": "https://icons.folo.is/www.cls.cn",
    "providerTitle": "财联社",
    "title": "电报",
    "capabilities": {
      "network": [
        "www.cls.cn"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "1m"
    },
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn",
    "id": "cls:telegraph"
  },
  {
    "icon": "https://icons.folo.is/www.cls.cn",
    "providerTitle": "财联社",
    "title": "深度",
    "capabilities": {
      "network": [
        "www.cls.cn"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn/depth",
    "id": "cls:depth"
  },
  {
    "icon": "https://icons.folo.is/www.cls.cn",
    "providerTitle": "财联社",
    "title": "热门",
    "capabilities": {
      "network": [
        "www.cls.cn"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "red",
    "type": "hottest",
    "category": "finance",
    "home": "https://www.cls.cn",
    "id": "cls:hot-article"
  },
  {
    "icon": "https://icons.folo.is/github.com",
    "providerTitle": "GitHub",
    "title": "Trending",
    "params": {
      "language": {
        "type": "text",
        "title": "Language",
        "description": "Programming language slug used by GitHub Trending, such as javascript, go, or rust.",
        "default": ""
      },
      "spokenLanguage": {
        "type": "text",
        "title": "Spoken Language",
        "description": "Repository description language code, such as en, zh, or ja.",
        "default": ""
      },
      "dateRange": {
        "type": "select",
        "title": "Date range",
        "values": [
          {
            "label": "Today",
            "value": "daily"
          },
          {
            "label": "This week",
            "value": "weekly"
          },
          {
            "label": "This month",
            "value": "monthly"
          }
        ],
        "default": "daily"
      }
    },
    "capabilities": {
      "network": [
        "github.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "15m"
    },
    "color": "slate",
    "type": "hottest",
    "category": "others",
    "home": "https://github.com/trending",
    "radar": [
      {
        "id": "github-trending",
        "match": {
          "hosts": [
            "github.com"
          ],
          "paths": [
            "/trending",
            "/trending/:language"
          ]
        },
        "patch": {
          "params": {
            "spokenLanguage": {
              "type": "query",
              "name": "spoken_language_code"
            },
            "dateRange": {
              "type": "query",
              "name": "since"
            }
          },
          "metadata": {
            "title": "Trending {{ params.language }}"
          }
        },
        "confidence": 0.95
      }
    ],
    "id": "github:trending"
  },
  {
    "icon": "https://icons.folo.is/news.ycombinator.com",
    "providerTitle": "Hacker News",
    "title": "Hottest",
    "capabilities": {
      "network": [
        "news.ycombinator.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "orange",
    "type": "hottest",
    "category": "others",
    "home": "https://news.ycombinator.com/",
    "id": "hackernews:top"
  },
  {
    "icon": "https://icons.folo.is/news.ycombinator.com",
    "providerTitle": "Hacker News",
    "title": "Newest",
    "capabilities": {
      "network": [
        "news.ycombinator.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "1m"
    },
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://news.ycombinator.com/newest",
    "id": "hackernews:newest"
  },
  {
    "icon": "https://icons.folo.is/news.ycombinator.com",
    "providerTitle": "Hacker News",
    "title": "Show",
    "capabilities": {
      "network": [
        "news.ycombinator.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/show",
    "id": "hackernews:show"
  },
  {
    "icon": "https://icons.folo.is/news.ycombinator.com",
    "providerTitle": "Hacker News",
    "title": "Ask",
    "capabilities": {
      "network": [
        "news.ycombinator.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/ask",
    "id": "hackernews:ask"
  },
  {
    "icon": "https://icons.folo.is/linux.do",
    "providerTitle": "Linux.do",
    "title": "Latest",
    "capabilities": {
      "network": [
        "linux.do"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "slate",
    "type": "timeline",
    "category": "tech",
    "home": "https://linux.do",
    "id": "linuxdo:latest"
  },
  {
    "icon": "https://icons.folo.is/linux.do",
    "providerTitle": "Linux.do",
    "title": "Hot",
    "capabilities": {
      "network": [
        "linux.do"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "slate",
    "type": "hottest",
    "category": "tech",
    "home": "https://linux.do",
    "id": "linuxdo:top-daily"
  },
  {
    "icon": "https://icons.folo.is/music.163.com",
    "providerTitle": "网易云音乐",
    "title": "飙升榜",
    "params": {
      "id": {
        "type": "text",
        "default": "19723756",
        "title": "Playlist",
        "pattern": "^\\d+$",
        "transforms": [
          {
            "type": "trim"
          }
        ]
      }
    },
    "capabilities": {
      "network": [
        "music.163.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "15m"
    },
    "color": "red",
    "type": "hottest",
    "category": "others",
    "home": "https://music.163.com/#/playlist?id=19723756",
    "radar": [
      {
        "id": "netease-music-playlist",
        "match": {
          "hosts": [
            "music.163.com",
            "y.music.163.com"
          ],
          "includes": [
            "playlist",
            "toplist"
          ]
        },
        "patch": {
          "metadata": {
            "title": "{% assign title = page.title | normalize_whitespace | regex_extract: '^(.+?)\\\\s*-\\\\s*(?:歌单|排行榜)\\\\s*-\\\\s*网易云音乐$', 1 %}{% if title != empty %}{{ title }}{% else %}Playlist {{ params.id }}{% endif %}"
          }
        },
        "confidence": 0.95
      }
    ],
    "id": "netease-music:playlist"
  },
  {
    "icon": "https://icons.folo.is/www.newsnow.com",
    "providerTitle": "NEWS NOW",
    "params": {
      "locale": {
        "type": "select",
        "values": [
          {
            "label": "US",
            "value": "us"
          },
          {
            "label": "UK",
            "value": "uk"
          },
          {
            "label": "Nigeria",
            "value": "ng"
          },
          {
            "label": "România",
            "value": "ro"
          },
          {
            "label": "Italia",
            "value": "it"
          },
          {
            "label": "Canada",
            "value": "ca"
          },
          {
            "label": "Australia",
            "value": "au"
          }
        ],
        "default": "us",
        "title": "Locale"
      },
      "topic": {
        "type": "text",
        "default": "US",
        "title": "Topic"
      }
    },
    "capabilities": {
      "network": [
        "www.newsnow.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "red",
    "type": "timeline",
    "category": "others",
    "home": "https://www.newsnow.com",
    "radar": [
      {
        "id": "newsnow-topic",
        "match": {
          "hosts": [
            "newsnow.com"
          ],
          "paths": [
            "/:locale/*topic"
          ]
        },
        "patch": {
          "metadata": {
            "title": "{{ params.topic }}"
          }
        },
        "confidence": 0.85
      }
    ],
    "id": "newsnow:topic-latest"
  },
  {
    "icon": "https://icons.folo.is/t.me",
    "providerTitle": "Telegram",
    "sourceIcon": "https://t.me/i/userpic/320/{{ params.channel | required | url_path }}.jpg",
    "title": "科技圈 在花频道",
    "params": {
      "channel": {
        "type": "text",
        "default": "TestFlightCN",
        "title": "Channel",
        "pattern": "^(?![\\d_])\\w{5,32}$",
        "transforms": [
          {
            "type": "trim"
          },
          {
            "type": "removePrefix",
            "value": "@"
          }
        ]
      }
    },
    "capabilities": {
      "network": [
        "t.me"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "blue",
    "type": "timeline",
    "category": "tech",
    "home": "https://t.me/s/TestFlightCN",
    "radar": [
      {
        "id": "telegram-channel",
        "match": {
          "hosts": [
            "t.me",
            "telegram.me"
          ],
          "paths": [
            "/s/:channel",
            "/:channel"
          ]
        },
        "patch": {
          "metadata": {
            "title": "{{ page.title | normalize_whitespace | regex_replace: '\\\\s*[–-]\\\\s*Telegram$', '' | default: 'Telegram channel' }}",
            "home": "https://t.me/s/{{ params.channel }}"
          }
        },
        "confidence": 0.95
      }
    ],
    "id": "telegram:channel"
  },
  {
    "icon": "https://icons.folo.is/tieba.baidu.com",
    "providerTitle": "百度贴吧",
    "title": "热议",
    "capabilities": {
      "network": [
        "tieba.baidu.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "blue",
    "type": "hottest",
    "category": "china",
    "home": "https://tieba.baidu.com",
    "id": "tieba:hot-topic"
  },
  {
    "icon": "https://icons.folo.is/v2ex.com",
    "providerTitle": "V2EX",
    "params": {
      "feed": {
        "type": "text",
        "title": "Feed",
        "default": "ideas",
        "pattern": ".+",
        "transforms": [
          {
            "type": "trim"
          }
        ]
      }
    },
    "capabilities": {
      "network": [
        "www.v2ex.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "slate",
    "category": "others",
    "home": "https://v2ex.com/",
    "radar": [
      {
        "id": "v2ex-feed",
        "match": {
          "hosts": [
            "v2ex.com"
          ],
          "paths": [
            "/go/:feed"
          ]
        },
        "patch": {
          "metadata": {
            "title": "{{ page.title | normalize_whitespace | regex_extract: '^.*[>›]\\\\s*(.+)$', 1 | default: params.feed }}"
          }
        },
        "confidence": 0.9
      }
    ],
    "id": "v2ex:feed"
  },
  {
    "icon": "https://icons.folo.is/xueqiu.com",
    "providerTitle": "雪球",
    "capabilities": {
      "network": [
        "stock.xueqiu.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://xueqiu.com",
    "id": "xueqiu:hot-stock"
  },
  {
    "icon": "https://icons.folo.is/www.zhihu.com",
    "providerTitle": "知乎",
    "title": "全站热榜",
    "capabilities": {
      "network": [
        "www.zhihu.com"
      ],
      "cookies": [],
      "browser": []
    },
    "cache": {
      "version": 1,
      "maxAge": "5m"
    },
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.zhihu.com",
    "id": "zhihu:hot-list"
  }
]
