// Auto-generated file - do not edit manually
// This file is generated by build.ts

import type { RuntimeSource } from "@newsnext/source-kit/types"
import type { ProviderConfig } from "@newsnext/source-kit/registry"
import {
  resolveProvider,
  resolveSourceRegistry,
} from "@newsnext/source-kit/registry"
import provider_0 from "./src/bilibili"
import provider_1 from "./src/cls"
import provider_2 from "./src/folo"
import provider_3 from "./src/jike/index"
import provider_4 from "./src/reddit/index"
import provider_5 from "./src/weibo/index"
import provider_6 from "./src/x/index"
import provider_7 from "./src/xueqiu"

const providerConfigs: Record<string, ProviderConfig> = {
  "bilibili": provider_0,
  "cls": provider_1,
  "folo": provider_2,
  "jike": provider_3,
  "reddit": provider_4,
  "weibo": provider_5,
  "x": provider_6,
  "xueqiu": provider_7
}

export const typescriptSources: Record<string, RuntimeSource> = Object.fromEntries(
  Object.entries(providerConfigs).flatMap(([providerId, providerConfig]) => {
    const provider = resolveProvider(providerId, providerConfig)
    return Object.entries(provider.sources).map(
      ([sourceId, source]) => [`${providerId}:${sourceId}`, source],
    )
  }),
)

export function resolveSources(registry: unknown): Record<string, RuntimeSource> {
  const registrySources = resolveSourceRegistry(registry)
  const typescriptProviderIds = new Set(
    Object.keys(typescriptSources).map(sourceId => sourceId.split(":", 1)[0]),
  )
  for (const sourceId of Object.keys(registrySources)) {
    const providerId = sourceId.split(":", 1)[0]
    if (providerId && typescriptProviderIds.has(providerId)) {
      throw new Error(`Provider "${providerId}" cannot mix JSON and TypeScript Sources`)
    }
  }
  return { ...registrySources, ...typescriptSources }
}
