import type { NewsItem, Source } from "@/typings/source"

const MOCK_TITLES_HOT = [
  "OpenAI Releases Latest GPT-5 Model with 10x Performance Improvement",
  "Tesla Announces Major Breakthrough in Full Self-Driving Technology",
  "Apple Spring Event: iPhone 16 Series Officially Unveiled",
  "Microsoft Acquires GitHub Copilot Competitor",
  "Meta Launches Next-Gen VR Headset, Price Drops to $299",
  "Google Quantum Computer Achieves Milestone Breakthrough",
  "Amazon AWS Launches AI Chip",
  "ByteDance Valuation Exceeds $300 Billion",
  "SpaceX Starship Completes First Manned Flight",
  "NVIDIA Releases Next-Gen GPU Architecture",
  "Alibaba Cloud Launches Self-Developed Large Model Service",
  "Tencent Games' New Title 'Dawn Awakening' Launches Globally",
  "BYD Electric Vehicle Sales Surpass Tesla",
  "Xiaomi Car SU7 Pre-orders Exceed 100,000",
  "Huawei HarmonyOS Global Users Exceed 500 Million",
  "Baidu Apollo Receives First Batch of Autonomous Driving Licenses",
  "OpenAI CEO Sam Altman Discusses AGI Development Path",
  "GitHub Copilot Launches Enterprise Edition with Private Deployment",
  "Rust Language Becomes Officially Supported in Linux Kernel",
  "TypeScript 5.5 Officially Released with Major Performance Improvements",
]

const MOCK_TITLES_TIMELINE = [
  "React 19 Beta Released with Compiler Optimizations",
  "Vue 3.5 Update: 30% Performance Improvement",
  "Next.js 15 Supports Native Rust Compilation",
  "Vite 6.0 Released with 2x Build Speed",
  "Tailwind CSS 4.0 Alpha Preview",
  "Bun 1.2 Released with Major Compatibility Improvements",
  "Deno 2.0 Officially Released",
  "Svelte 5 Introduces New Reactive System",
  "Astro 5.0 Supports Server Components",
  "Nuxt 4 Development Roadmap Announced",
  "Remix 3.0 Beta Testing Begins",
  "SolidJS 2.0 Performance Benchmark Results Published",
  "Qwik Framework Receives Google Investment",
  "Turbopack Enters Stable Version",
  "ESLint 10 Supports Flat Configuration",
  "Prettier 4.0 Rewrites Core Engine",
  "Vitest 2.0 Released with Browser Mode Support",
  "Playwright 2.0 Adds AI Testing Features",
  "Webpack 6 Development Plan Announced",
  "Rollup 5.0 Optimizes Tree-shaking Algorithm",
]

export const MOCK_ITEMS_HOT: NewsItem[] = Array.from({ length: 20 }).map((_, i) => ({
  id: i,
  title: MOCK_TITLES_HOT[i],
  url: "https://example.com",
  extra: {
    diff: i % 4 === 0 ? (i % 2 === 0 ? 1 : -1) : undefined,
    info: i % 3 === 0 ? `${Math.floor(Math.random() * 500) + 10} comments` : undefined,
  },
}))

export const MOCK_ITEMS_TIMELINE: NewsItem[] = Array.from({ length: 20 }).map((_, i) => ({
  id: i,
  title: MOCK_TITLES_TIMELINE[i],
  url: "https://example.com",
  pubDate: Date.now() - i * 1000 * 60 * 30, // Each news item is 30 minutes apart
  extra: {
    date: Date.now() - i * 1000 * 60 * 30,
  },
}))

export const MOCK_SOURCES: Record<string, Source & { id: string }> = {
  "36kr": {
    id: "36kr",
    name: "36Kr",
    color: "blue",
    title: "Latest",
    type: "hottest",
    home: "https://36kr.com",
    desc: "36Kr - Making Entrepreneurship Easier",
    interval: 60,
  },
  "v2ex": {
    id: "v2ex",
    name: "V2EX",
    color: "gray",
    type: "normal",
    home: "https://v2ex.com",
    desc: "V2EX - A Community for Creative Workers",
    interval: 60,
  },
  "github": {
    id: "github",
    name: "GitHub",
    color: "gray",
    type: "hottest",
    home: "https://github.com",
    desc: "GitHub Trending - Today's Hot Open Source Projects",
    interval: 60,
  },
  "zhihu": {
    id: "zhihu",
    name: "Zhihu",
    color: "blue",
    type: "hottest",
    home: "https://zhihu.com",
    desc: "Zhihu Hot - Where Questions Find Answers",
    interval: 60,
  },
  "juejin": {
    id: "juejin",
    name: "Juejin",
    color: "blue",
    type: "normal",
    home: "https://juejin.cn",
    desc: "Juejin - Code Never Stops, Mining Never Ends",
    interval: 60,
  },
  "ithome": {
    id: "ithome",
    name: "IT Home",
    color: "red",
    type: "normal",
    home: "https://ithome.com",
    desc: "IT Home - Digital Technology News",
    interval: 60,
  },
  "weibo": {
    id: "weibo",
    name: "Weibo",
    color: "red",
    type: "hottest",
    home: "https://weibo.com",
    desc: "Weibo Hot Search",
    interval: 60,
  },
  "bilibili": {
    id: "bilibili",
    name: "Bilibili",
    color: "blue",
    type: "hottest",
    home: "https://bilibili.com",
    desc: "Bilibili Popular Videos",
    interval: 60,
  },
}
