import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
// import { build } from "tsdown"

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = __dirname

const glob = new Bun.Glob("src/lib/*.ts")
const deepIndexGlob = new Bun.Glob("src/lib/**/index.ts")
const SRC_PREFIX_REGEX = /^src\//
const TS_EXTENSION_REGEX = /\.ts$/

const files = new Set<string>()

for await (const file of glob.scan(rootDir)) {
  files.add(file)
}

for await (const file of deepIndexGlob.scan(rootDir)) {
  files.add(file)
}

// Sort files for consistent output
const sortedFiles = Array.from(files).sort()

// Generate import statements and entries
const importStatements: string[] = []
const providerEntries: string[] = []

sortedFiles.forEach((file, index) => {
  // Remove src/ prefix and .ts extension, convert to relative import path
  const importPath = `./${file.replace(SRC_PREFIX_REGEX, "").replace(TS_EXTENSION_REGEX, "")}`

  // Extract key from path
  const pathParts = importPath.split("/")
  const key = pathParts[pathParts.length - 1] === "index"
    ? pathParts[pathParts.length - 2]
    : pathParts[pathParts.length - 1]

  const alias = `provider_${index}`
  importStatements.push(`import ${alias} from "${importPath}"`)
  providerEntries.push(`  [${alias}.id ?? ${JSON.stringify(key)}]: ${alias}`)
})

const indexContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts

${importStatements.join("\n")}

export const providers = {
${providerEntries.join(",\n")}
}
`

const indexPath = join(rootDir, "src", "index.ts")
await Bun.file(indexPath).write(indexContent)

// Generate metadata.ts
const { providers } = await import(`${indexPath}?updated=${Date.now()}`)
console.log("Found providers:", Object.keys(providers))

const sourceDescriptors = []
for (const [provider, providerDefinition] of Object.entries(providers)) {
  for (const [sourceId, source] of Object.entries((providerDefinition as any).sources)) {
    const { loader, ...meta } = source as any
    const key = meta.key || sourceId
    const descriptor = { ...meta }
    delete descriptor.key
    sourceDescriptors.push({
      ...descriptor,
      icon: descriptor.icon ?? `https://s3.newsnext.pro/icons/${provider}.png`,
      id: `${provider}:${key}`,
    })
  }
}

const metadataContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "@newsnext/source-shared/typings"

export const sourceDescriptors: SourceDescriptor[] = ${JSON.stringify(sourceDescriptors, null, 2)}
`

await Bun.file(join(rootDir, "src", "metadata.ts")).write(metadataContent)
console.log("Generated src/metadata.ts with", sourceDescriptors.length, "entries")

// await build({
//   entry: indexPath,
//   outDir: join(rootDir, "dist"),
//   dts: true,
// })
