// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionOutcome } from "./CollectionOutcome.js";

export type CollectionPolicyStatus = { intervalMs: number, nextRunAt: number, lastFetchedAt: number | null, lastAttemptAt: number | null, lastChangedAt: number | null, lastError: string | null, lastOutcome: CollectionOutcome | null, added: number, removed: number, edited: number, moved: number, };
