// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamStatus } from "./StreamStatus.js";

export type CollectionStatus = { initialized: boolean, sampledAt: number, persistenceError: string | null, pendingWrites: number, streams: Array<StreamStatus>, };
