// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Worker } from "@newsnext/sdk/models";
import type { Workspace } from "./Workspace.js";

export type ExtensionToHost = { "type": "rpc", message: unknown, } | { "type": "hello", protocolVersion: number, worker: Worker, workspace: Workspace, };
