// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandResult } from "./CommandResult.js";
import type { Worker } from "@newsnext/sdk/models";
import type { Workspace } from "./Workspace.js";
import type { WorkspacePatch } from "./WorkspacePatch.js";

export type ExtensionToHost = { "type": "sdkRequest", requestId: string, request: unknown, } | { "type": "sdkNext", requestId: string, } | { "type": "sdkCancel", requestId: string, } | { "type": "hello", protocolVersion: number, worker: Worker, workspace: Workspace, } | { "type": "complete", requestId: string, result: CommandResult, } | { "type": "workspaceChanged", requestId: string, patch: WorkspacePatch, } | { "type": "widgetSnapshotGet", requestId: string, boardId: string, widgetId: string, } | { "type": "instanceGet", requestId: string, instanceId: string, cacheOnly: boolean, } | { "type": "collectionStatusSubscribe", enabled: boolean, } | { "type": "collectionStatusGet", requestId: string, } | { "type": "logsGet", requestId: string, } | { "type": "workerTakeover", requestId: string, workerId: string, instanceIds: Array<string>, };
