// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsightCatalogEntry } from "@newsnext/sdk/models";
import type { OfflineWorker } from "@newsnext/sdk/models";
import type { Workspace } from "./Workspace.js";

export type HostToExtension = { "type": "rpc", message: unknown, } | { "type": "chunk", transferId: string, index: number, total: number, data: string, } | { "type": "ready", protocolVersion: number, daemonVersion: string, capabilities: Array<string>, insightServerUrl: string, insights: Array<InsightCatalogEntry>, workspace: Workspace, localCardIds: Array<string>, workerRoutingRevision: number, offlineWorkers: Array<OfflineWorker>, localSources: Record<string, unknown>, } | { "type": "error", requestId: string | null, code?: string, message: string, };
