// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveWidgetDataScope } from "./LiveWidgetDataScope.js";
import type { LiveWidgetLayout } from "./LiveWidgetLayout.js";
import type { WidgetPatch } from "./WidgetPatch.js";

export type LiveWidget = { patch?: WidgetPatch, dataScope: LiveWidgetDataScope, layout: LiveWidgetLayout, widgetId: string, };
