// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveWidgetDataScope } from "./LiveWidgetDataScope.js";
import type { LiveWidgetLayout } from "./LiveWidgetLayout.js";
import type { WidgetMetadata } from "./WidgetMetadata.js";

export type LiveWidget = { metadata?: WidgetMetadata, params?: Record<string, unknown>, dataScope: LiveWidgetDataScope, layout: LiveWidgetLayout, widgetId: string, };
