// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widget size in half-LiveCard units. Placement order is the array order of
 * the Board's Next Layer Widgets; there are no coordinates.
 */
export type LiveWidgetLayout = { height: number, width: number, };
