// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionStatus } from "./CollectionStatus.js";
import type { OfflineWorker } from "@newsnext/sdk/models";
import type { WidgetCatalogEntry } from "@newsnext/sdk/models";
import type { WorkspacePatch } from "./WorkspacePatch.js";

export type NativeNotification = { "method": "workerRoutingChanged", "params": { revision: number, localCardIds: Array<string>, offlineWorkers: Array<OfflineWorker>, } } | { "method": "workspaceChanged", "params": { patch: WorkspacePatch, localCardIds: Array<string>, } } | { "method": "collectionStatusChanged", "params": { status: CollectionStatus, } } | { "method": "widgetCatalogChanged", "params": { widgets: Array<WidgetCatalogEntry>, } };
