// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveWidget } from "./LiveWidget.js";

export type NextLayer = { liveWidgets: Array<LiveWidget>, };
