// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextLayerWidgetDataScope } from "./NextLayerWidgetDataScope.js";
import type { NextLayerWidgetLayout } from "./NextLayerWidgetLayout.js";
import type { WidgetMetadata } from "./WidgetMetadata.js";

export type NextLayerWidget = { metadata?: WidgetMetadata, params?: Record<string, unknown>, dataScope: NextLayerWidgetDataScope, layout: NextLayerWidgetLayout, widgetId: string, };
