// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Board's Now layer. Array order is display order; new entries prepend.
 */
export type NowLayer = { liveCards: Array<string>, };
