// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NowLayerSortMode } from "./NowLayerSortMode.js";

export type NowLayerSort = { mode: NowLayerSortMode, automaticMode: NowLayerSortMode, manualOrder: Array<string>, };
