// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionActivity } from "./CollectionActivity.js";
import type { CollectionPolicyStatus } from "./CollectionPolicyStatus.js";

export type StreamStatus = { streamId: string, sourceId: string, workerId: string, instanceIds: Array<string>, resolved: boolean, observationCount?: number | null, activity: CollectionActivity, policy: CollectionPolicyStatus, };
