// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetMetadata } from "./WidgetMetadata.js";

export type WidgetPatch = { metadata?: WidgetMetadata, params?: Record<string, unknown>, view?: Record<string, unknown>, };
