// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceBoard } from "./WorkspaceBoard.js";
import type { WorkspaceLiveCard } from "./WorkspaceLiveCard.js";

export type WorkspacePatch = { expectedRevision: number, updatedAt: number, boardOrder: Array<string>, boards: Array<WorkspaceBoard>, cardOrder: Array<string>, liveCards: Array<WorkspaceLiveCard>, settings: string, };
