// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveWidget } from "./LiveWidget.js";
import type { WorkspaceBoard } from "./WorkspaceBoard.js";
import type { WorkspaceLiveCard } from "./WorkspaceLiveCard.js";

export type WorkspacePatch = { expectedRevision: number, updatedAt: number, boardOrder: Array<string>, boards: { [key in string]: WorkspaceBoard }, liveCards: { [key in string]: WorkspaceLiveCard }, liveWidgets: { [key in string]: LiveWidget }, settings: string, };
