// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceBoard } from "./WorkspaceBoard.js";
import type { WorkspaceLiveCard } from "./WorkspaceLiveCard.js";

export type Workspace = { revision: number, updatedAt: number, boards: Array<WorkspaceBoard>, liveCards: Array<WorkspaceLiveCard>, settings: string, };
