// Auto-generated file - do not edit manually
// This file is generated by build.ts

import provider_0 from "./lib/aihot"
import provider_1 from "./lib/bilibili"
import provider_2 from "./lib/browser"
import provider_3 from "./lib/cls"
import provider_4 from "./lib/folo"
import provider_5 from "./lib/github"
import provider_6 from "./lib/hackernews"
import provider_7 from "./lib/jike/index"
import provider_8 from "./lib/linuxdo"
import provider_9 from "./lib/netease-music"
import provider_10 from "./lib/newsnow"
import provider_11 from "./lib/tieba"
import provider_12 from "./lib/v2ex"
import provider_13 from "./lib/weibo"
import provider_14 from "./lib/x/index"
import provider_15 from "./lib/xueqiu"
import provider_16 from "./lib/zaobao"
import provider_17 from "./lib/zhihu"

export const providers = {
  [provider_0.id ?? "aihot"]: provider_0,
  [provider_1.id ?? "bilibili"]: provider_1,
  [provider_2.id ?? "browser"]: provider_2,
  [provider_3.id ?? "cls"]: provider_3,
  [provider_4.id ?? "folo"]: provider_4,
  [provider_5.id ?? "github"]: provider_5,
  [provider_6.id ?? "hackernews"]: provider_6,
  [provider_7.id ?? "jike"]: provider_7,
  [provider_8.id ?? "linuxdo"]: provider_8,
  [provider_9.id ?? "netease-music"]: provider_9,
  [provider_10.id ?? "newsnow"]: provider_10,
  [provider_11.id ?? "tieba"]: provider_11,
  [provider_12.id ?? "v2ex"]: provider_12,
  [provider_13.id ?? "weibo"]: provider_13,
  [provider_14.id ?? "x"]: provider_14,
  [provider_15.id ?? "xueqiu"]: provider_15,
  [provider_16.id ?? "zaobao"]: provider_16,
  [provider_17.id ?? "zhihu"]: provider_17
}
