/* eslint-disable */
// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "@newsnext/source-shared/typings"

export const sourceDescriptors: SourceDescriptor[] = [
  {
    "icon": "https://s3.newsnext.pro/icons/aihot.png",
    "providerTitle": "AIHot",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "timeline",
    "category": "tech",
    "home": "https://aihot.virxact.com",
    "id": "aihot:all"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "热搜",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:hotword"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "关注视频",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "desc": "关注 UP 的视频动态",
    "type": "timeline",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:following-videos"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "排行榜",
    "params": {
      "region": {
        "type": "select",
        "title": "Region",
        "options": [
          {
            "label": "All",
            "value": "0"
          },
          {
            "label": "Animation",
            "value": "1"
          },
          {
            "label": "Anime",
            "value": "13"
          },
          {
            "label": "Guochuang",
            "value": "167"
          },
          {
            "label": "Music",
            "value": "3"
          },
          {
            "label": "Dance",
            "value": "129"
          },
          {
            "label": "Games",
            "value": "4"
          },
          {
            "label": "Knowledge",
            "value": "36"
          },
          {
            "label": "Technology",
            "value": "188"
          },
          {
            "label": "Sports",
            "value": "234"
          },
          {
            "label": "Cars",
            "value": "223"
          },
          {
            "label": "Life",
            "value": "160"
          },
          {
            "label": "Food",
            "value": "211"
          },
          {
            "label": "Animals",
            "value": "217"
          },
          {
            "label": "Kichiku",
            "value": "119"
          },
          {
            "label": "Fashion",
            "value": "155"
          },
          {
            "label": "Entertainment",
            "value": "5"
          },
          {
            "label": "Film & TV",
            "value": "181"
          },
          {
            "label": "Documentary",
            "value": "177"
          },
          {
            "label": "Movies",
            "value": "23"
          },
          {
            "label": "TV Series",
            "value": "11"
          }
        ],
        "default": "0"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:ranking"
  },
  {
    "icon": "https://www.google.com/chrome/static/images/favicons/favicon-96x96.png",
    "providerTitle": "Browser",
    "title": "History",
    "params": {
      "query": {
        "type": "text",
        "title": "Search",
        "default": ""
      },
      "dateRange": {
        "type": "select",
        "title": "Date range",
        "options": [
          {
            "label": "Today",
            "value": "today"
          },
          {
            "label": "Last 7 days",
            "value": "week"
          },
          {
            "label": "Last 30 days",
            "value": "month"
          },
          {
            "label": "All history",
            "value": "all"
          }
        ],
        "default": "week"
      },
      "maxResults": {
        "type": "number",
        "title": "Limit",
        "default": 50,
        "min": 1,
        "max": 100
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "timeline",
    "category": "others",
    "id": "browser:history"
  },
  {
    "icon": "https://www.google.com/chrome/static/images/favicons/favicon-96x96.png",
    "providerTitle": "Browser",
    "title": "Bookmarks",
    "params": {
      "folder": {
        "type": "text",
        "title": "Folder",
        "description": "Leave empty to include every bookmark. Use a folder ID, title, or path.",
        "default": ""
      },
      "maxResults": {
        "type": "number",
        "title": "Limit",
        "default": 50,
        "min": 1,
        "max": 200
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "timeline",
    "category": "others",
    "id": "browser:bookmarks"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "电报",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn/telegraph",
    "id": "cls:telegraph"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "深度",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn/depth",
    "id": "cls:depth"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "热门",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "type": "hottest",
    "category": "finance",
    "home": "https://www.cls.cn",
    "id": "cls:hot-article"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/folo.png",
    "providerTitle": "Folo",
    "title": "Feed",
    "params": {
      "feedId": {
        "type": "text",
        "title": "Feed ID",
        "default": "71931642168770560"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://folo.is",
    "id": "folo:feed"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/folo.png",
    "providerTitle": "Folo",
    "title": "List",
    "params": {
      "listId": {
        "type": "text",
        "title": "List ID",
        "default": "68649150114432000"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://folo.is",
    "id": "folo:list"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/github.png",
    "providerTitle": "GitHub",
    "title": "Trending",
    "params": {
      "language": {
        "type": "text",
        "title": "Language",
        "description": "Programming language slug used by GitHub Trending, such as javascript, go, or rust.",
        "default": ""
      },
      "spokenLanguage": {
        "type": "text",
        "title": "Spoken Language",
        "description": "Repository description language code, such as en, zh, or ja.",
        "default": ""
      },
      "dateRange": {
        "type": "select",
        "title": "Date range",
        "options": [
          {
            "label": "Today",
            "value": "daily"
          },
          {
            "label": "This week",
            "value": "weekly"
          },
          {
            "label": "This month",
            "value": "monthly"
          }
        ],
        "default": "daily"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "type": "hottest",
    "category": "others",
    "home": "https://github.com/trending",
    "radar": [
      {
        "id": "github-trending",
        "match": {
          "hosts": [
            "github.com"
          ],
          "paths": [
            "/trending",
            "/trending/:language"
          ]
        },
        "title": {
          "type": "template",
          "value": "Trending {language}"
        },
        "params": {
          "language": {
            "type": "path",
            "name": "language"
          },
          "spokenLanguage": {
            "type": "query",
            "name": "spoken_language_code"
          },
          "dateRange": {
            "value": {
              "type": "first",
              "values": [
                {
                  "type": "query",
                  "name": "since"
                },
                {
                  "type": "literal",
                  "value": "daily"
                }
              ]
            },
            "in": [
              "daily",
              "weekly",
              "monthly"
            ]
          }
        },
        "confidence": 0.95
      }
    ],
    "id": "github:trending"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Hottest",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "orange",
    "type": "hottest",
    "category": "others",
    "home": "https://news.ycombinator.com/",
    "id": "hackernews:top"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Newest",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://news.ycombinator.com/newest",
    "id": "hackernews:newest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Show",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/show",
    "id": "hackernews:show"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Ask",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/ask",
    "id": "hackernews:ask"
  },
  {
    "icon": "https://web.okjike.com/favicon.ico",
    "providerTitle": "Jike",
    "title": "Following updates",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "yellow",
    "desc": "Updates from followed Jike users",
    "type": "timeline",
    "category": "others",
    "home": "https://web.okjike.com",
    "secrets": [
      {
        "key": "accessToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_ACCESS_TOKEN"
      },
      {
        "key": "refreshToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_REFRESH_TOKEN"
      }
    ],
    "id": "jike:following-updates"
  },
  {
    "icon": "https://web.okjike.com/favicon.ico",
    "providerTitle": "Jike",
    "title": "User updates",
    "params": {
      "username": {
        "type": "text",
        "title": "Username",
        "default": "a2d6acc1-626f-4d15-a22a-849e88a4c9f0"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "yellow",
    "desc": "Updates from a Jike user",
    "type": "timeline",
    "category": "others",
    "home": "https://web.okjike.com",
    "secrets": [
      {
        "key": "accessToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_ACCESS_TOKEN"
      },
      {
        "key": "refreshToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_REFRESH_TOKEN"
      }
    ],
    "radar": [
      {
        "id": "jike-user-profile",
        "match": {
          "hosts": [
            "web.okjike.com"
          ],
          "paths": [
            "/u/:username"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "replace",
              "pattern": "的主页\\s*[-_—|]\\s*即刻.*$",
              "replacement": ""
            },
            {
              "type": "extract",
              "pattern": "^(.+?)(?:\\s*[-_—|]\\s*即刻.*)?$",
              "fallbackToEmpty": true
            }
          ],
          "fallback": "{username}"
        },
        "params": {
          "username": {
            "value": {
              "type": "path",
              "name": "username"
            },
            "required": true
          }
        },
        "confidence": 0.9
      },
      {
        "id": "jike-user-post",
        "match": {
          "hosts": [
            "web.okjike.com"
          ],
          "paths": [
            "/u/:username/:type/:id{/*rest}"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "extract",
              "pattern": "^(.+?)[:：]"
            },
            {
              "type": "extract",
              "pattern": "^(.+?)(?:\\s*[-_—|]\\s*即刻.*)?$",
              "fallbackToEmpty": true
            }
          ],
          "fallback": "{username}"
        },
        "params": {
          "username": {
            "value": {
              "type": "path",
              "name": "username"
            },
            "required": true
          }
        },
        "confidence": 0.9
      }
    ],
    "id": "jike:user-updates"
  },
  {
    "icon": "https://web.okjike.com/favicon.ico",
    "providerTitle": "Jike",
    "title": "Topic recent",
    "params": {
      "topicId": {
        "type": "text",
        "title": "Topic ID",
        "default": "5aeaa84029e4000011ac3768"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "yellow",
    "desc": "Recent posts from a Jike topic",
    "type": "timeline",
    "category": "others",
    "home": "https://web.okjike.com",
    "secrets": [
      {
        "key": "accessToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_ACCESS_TOKEN"
      },
      {
        "key": "refreshToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_REFRESH_TOKEN"
      }
    ],
    "radar": [
      {
        "id": "jike-topic-recent",
        "match": {
          "hosts": [
            "web.okjike.com"
          ],
          "paths": [
            "/topic/:topicId{/*rest}"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "extract",
              "pattern": "^(.+?)(?:\\s*[-_—|]\\s*即刻.*)?$",
              "fallbackToEmpty": true
            }
          ],
          "fallback": "Topic {topicId}"
        },
        "params": {
          "topicId": {
            "value": {
              "type": "path",
              "name": "topicId"
            },
            "required": true
          }
        },
        "confidence": 0.9
      }
    ],
    "id": "jike:topic-recent"
  },
  {
    "icon": "https://web.okjike.com/favicon.ico",
    "providerTitle": "Jike",
    "title": "Topic hottest",
    "params": {
      "topicId": {
        "type": "text",
        "title": "Topic ID",
        "default": "5aeaa84029e4000011ac3768"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "yellow",
    "desc": "Hottest posts from a Jike topic",
    "type": "hottest",
    "category": "others",
    "home": "https://web.okjike.com",
    "secrets": [
      {
        "key": "accessToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_ACCESS_TOKEN"
      },
      {
        "key": "refreshToken",
        "type": "localStorage",
        "origin": "https://web.okjike.com",
        "itemKey": "JK_REFRESH_TOKEN"
      }
    ],
    "radar": [
      {
        "id": "jike-topic-hottest",
        "match": {
          "hosts": [
            "web.okjike.com"
          ],
          "paths": [
            "/topic/:topicId{/*rest}"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "extract",
              "pattern": "^(.+?)(?:\\s*[-_—|]\\s*即刻.*)?$",
              "fallbackToEmpty": true
            }
          ],
          "fallback": "Topic {topicId}"
        },
        "params": {
          "topicId": {
            "value": {
              "type": "path",
              "name": "topicId"
            },
            "required": true
          }
        },
        "confidence": 0.85
      }
    ],
    "id": "jike:topic-hottest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/linuxdo.png",
    "providerTitle": "Linux.do",
    "title": "Latest",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "type": "timeline",
    "category": "tech",
    "home": "https://linux.do",
    "id": "linuxdo:latest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/linuxdo.png",
    "providerTitle": "Linux.do",
    "title": "Hot",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "type": "hottest",
    "category": "tech",
    "home": "https://linux.do",
    "id": "linuxdo:top-daily"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/netease-music.png",
    "providerTitle": "网易云音乐",
    "title": "飙升榜",
    "params": {
      "id": {
        "type": "text",
        "default": "19723756",
        "title": "Playlist"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "type": "hottest",
    "category": "others",
    "home": "https://music.163.com/#/playlist?id=19723756",
    "radar": [
      {
        "id": "netease-music-playlist",
        "match": {
          "hosts": [
            "music.163.com",
            "y.music.163.com"
          ],
          "includes": [
            "playlist",
            "toplist"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "extract",
              "pattern": "^(.+?)\\s*-\\s*(?:歌单|排行榜)\\s*-\\s*网易云音乐$",
              "fallbackToEmpty": true
            }
          ],
          "fallback": "Playlist {id}"
        },
        "params": {
          "id": {
            "value": {
              "type": "first",
              "values": [
                {
                  "type": "query",
                  "name": "id"
                },
                {
                  "type": "hashQuery",
                  "name": "id"
                }
              ]
            },
            "pattern": "^\\d+$"
          }
        },
        "confidence": 0.95
      }
    ],
    "id": "netease-music:playlist"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/newsnow.png",
    "providerTitle": "NEWS NOW",
    "params": {
      "locale": {
        "type": "select",
        "options": [
          {
            "label": "US",
            "value": "us"
          },
          {
            "label": "UK",
            "value": "uk"
          },
          {
            "label": "Nigeria",
            "value": "ng"
          },
          {
            "label": "România",
            "value": "ro"
          },
          {
            "label": "Italia",
            "value": "it"
          },
          {
            "label": "Canada",
            "value": "ca"
          },
          {
            "label": "Australia",
            "value": "au"
          }
        ],
        "default": "us",
        "title": "Locale"
      },
      "topic": {
        "type": "text",
        "default": "US",
        "title": "Topic"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "type": "timeline",
    "category": "others",
    "home": "https://www.newsnow.com",
    "radar": [
      {
        "id": "newsnow-topic",
        "match": {
          "hosts": [
            "newsnow.com"
          ],
          "paths": [
            "/:locale/*topic"
          ]
        },
        "title": {
          "type": "param",
          "name": "topic"
        },
        "params": {
          "locale": {
            "value": {
              "type": "path",
              "name": "locale"
            },
            "in": [
              "us",
              "uk",
              "ng",
              "ro",
              "it",
              "ca",
              "au"
            ]
          },
          "topic": {
            "value": {
              "type": "path",
              "name": "topic"
            },
            "required": true
          }
        },
        "confidence": 0.85
      }
    ],
    "id": "newsnow:topic-latest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/tieba.png",
    "providerTitle": "百度贴吧",
    "title": "热议",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "hottest",
    "category": "china",
    "home": "https://tieba.baidu.com",
    "id": "tieba:hot-topic"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/v2ex.png",
    "providerTitle": "V2EX",
    "params": {
      "feed": {
        "type": "text",
        "title": "Feed",
        "default": "ideas"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "category": "others",
    "home": "https://v2ex.com/",
    "radar": [
      {
        "id": "v2ex-feed",
        "match": {
          "hosts": [
            "v2ex.com"
          ],
          "paths": [
            "/go/:feed"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "extract",
              "pattern": "^.*[>›]\\s*(.+)$"
            }
          ],
          "fallback": "{feed}"
        },
        "params": {
          "feed": {
            "value": {
              "type": "path",
              "name": "feed"
            },
            "required": true
          }
        },
        "confidence": 0.9
      }
    ],
    "id": "v2ex:feed"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/weibo.png",
    "providerTitle": "Weibo",
    "title": "Hot Search",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "type": "hottest",
    "category": "others",
    "home": "https://s.m.weibo.cn/top/summary?cate=realtimehot",
    "id": "weibo:hot-search"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/weibo.png",
    "providerTitle": "Weibo",
    "title": "User Posts",
    "params": {
      "uid": {
        "type": "text",
        "title": "User ID",
        "description": "Numeric uid, or a Weibo profile URL containing the uid.",
        "default": "1195230310"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "desc": "Latest posts from a specified Weibo user",
    "type": "timeline",
    "category": "others",
    "home": "https://m.weibo.cn",
    "secrets": [
      {
        "key": "sub",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUB",
        "required": false
      },
      {
        "key": "subp",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUBP",
        "required": false
      },
      {
        "key": "ssoLoginState",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SSOLoginState",
        "required": false
      }
    ],
    "radar": [
      {
        "id": "weibo-user",
        "match": {
          "hosts": [
            "m.weibo.cn",
            "weibo.com"
          ],
          "paths": [
            "/u/:uid",
            "/profile/:uid"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "extract",
              "pattern": "^@(.+)\\s*的个人主页"
            },
            {
              "type": "replace",
              "pattern": "[-_—|].*微博.*$",
              "replacement": ""
            },
            {
              "type": "replace",
              "pattern": "的微博.*$",
              "replacement": ""
            }
          ],
          "fallback": "User {uid}"
        },
        "params": {
          "uid": {
            "value": {
              "type": "path",
              "name": "uid"
            },
            "pattern": "^\\d+$"
          }
        },
        "confidence": 0.9
      }
    ],
    "id": "weibo:user"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/weibo.png",
    "providerTitle": "Weibo",
    "title": "Keyword",
    "params": {
      "keyword": {
        "type": "text",
        "title": "Keyword",
        "default": "MSI"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "desc": "Latest Weibo posts matching a keyword",
    "type": "timeline",
    "category": "others",
    "home": "https://m.weibo.cn",
    "secrets": [
      {
        "key": "sub",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUB",
        "required": false
      },
      {
        "key": "subp",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUBP",
        "required": false
      },
      {
        "key": "ssoLoginState",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SSOLoginState",
        "required": false
      }
    ],
    "radar": [
      {
        "id": "weibo-keyword",
        "match": {
          "hosts": [
            "s.weibo.com",
            "s.m.weibo.cn"
          ]
        },
        "title": {
          "type": "param",
          "name": "keyword"
        },
        "params": {
          "keyword": {
            "value": {
              "type": "first",
              "values": [
                {
                  "type": "query",
                  "name": "q"
                },
                {
                  "type": "query",
                  "name": "keyword"
                }
              ]
            },
            "required": true
          }
        },
        "confidence": 0.9
      }
    ],
    "id": "weibo:keyword"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/weibo.png",
    "providerTitle": "Weibo",
    "title": "Super Topic",
    "params": {
      "id": {
        "type": "text",
        "title": "Super topic ID",
        "description": "A 100808... super topic ID, or a Weibo super topic URL containing it.",
        "default": "1008084989d223732bf6f02f75ea30efad58a9"
      },
      "type": {
        "type": "select",
        "title": "Type",
        "options": [
          {
            "label": "Latest comments",
            "value": "feed"
          },
          {
            "label": "Latest posts",
            "value": "sort_time"
          },
          {
            "label": "Hot",
            "value": "hot_sort"
          },
          {
            "label": "Featured",
            "value": "soul"
          }
        ],
        "default": "feed"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "desc": "Latest posts from a Weibo super topic",
    "type": "timeline",
    "category": "others",
    "home": "https://m.weibo.cn",
    "secrets": [
      {
        "key": "sub",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUB",
        "required": false
      },
      {
        "key": "subp",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUBP",
        "required": false
      },
      {
        "key": "ssoLoginState",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SSOLoginState",
        "required": false
      }
    ],
    "radar": [
      {
        "id": "weibo-super-topic",
        "match": {
          "hosts": [
            "m.weibo.cn",
            "weibo.com"
          ]
        },
        "title": {
          "type": "value",
          "value": {
            "type": "pageTitle"
          },
          "transforms": [
            {
              "type": "normalizeWhitespace"
            },
            {
              "type": "replace",
              "pattern": "[-_—|].*微博.*$",
              "replacement": ""
            },
            {
              "type": "replace",
              "pattern": "的微博.*$",
              "replacement": ""
            },
            {
              "type": "extract",
              "pattern": "^#?(.+?)超话#?$"
            }
          ],
          "fallback": "{id}"
        },
        "params": {
          "id": {
            "value": {
              "type": "first",
              "values": [
                {
                  "type": "query",
                  "name": "containerid"
                },
                {
                  "type": "hashQuery",
                  "name": "containerid"
                },
                {
                  "type": "pathSegmentWithPrefix",
                  "prefix": "100808"
                }
              ]
            },
            "startsWith": "100808"
          },
          "type": {
            "type": "literal",
            "value": "feed"
          }
        },
        "confidence": 0.9
      }
    ],
    "id": "weibo:super-topic"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/weibo.png",
    "providerTitle": "Weibo",
    "title": "Following Timeline",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "desc": "Latest posts from all followed Weibo accounts",
    "type": "timeline",
    "category": "others",
    "home": "https://m.weibo.cn",
    "secrets": [
      {
        "key": "sub",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUB",
        "required": true
      },
      {
        "key": "subp",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SUBP",
        "required": false
      },
      {
        "key": "ssoLoginState",
        "type": "cookie",
        "origin": "https://m.weibo.cn",
        "itemKey": "SSOLoginState",
        "required": false
      }
    ],
    "id": "weibo:following"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "Trending",
    "params": {
      "location": {
        "type": "select",
        "title": "Location",
        "options": [
          {
            "label": "Worldwide",
            "value": "1"
          },
          {
            "label": "United States",
            "value": "23424977"
          },
          {
            "label": "United Kingdom",
            "value": "23424975"
          },
          {
            "label": "Japan",
            "value": "23424856"
          },
          {
            "label": "Hong Kong",
            "value": "24865698"
          },
          {
            "label": "Taiwan",
            "value": "23424971"
          },
          {
            "label": "Singapore",
            "value": "23424948"
          },
          {
            "label": "India",
            "value": "23424848"
          },
          {
            "label": "Brazil",
            "value": "23424768"
          },
          {
            "label": "Germany",
            "value": "23424829"
          }
        ],
        "default": "1"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "type": "hottest",
    "category": "world",
    "home": "https://x.com",
    "secrets": [
      {
        "key": "csrfToken",
        "type": "cookie",
        "origin": "https://x.com",
        "itemKey": "ct0",
        "cache": false
      }
    ],
    "id": "x:place-trends"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "Recommended",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "type": "timeline",
    "category": "world",
    "home": "https://x.com",
    "secrets": [
      {
        "key": "csrfToken",
        "type": "cookie",
        "origin": "https://x.com",
        "itemKey": "ct0",
        "cache": false
      }
    ],
    "id": "x:recommended"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "Following",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "type": "timeline",
    "category": "world",
    "home": "https://x.com",
    "secrets": [
      {
        "key": "csrfToken",
        "type": "cookie",
        "origin": "https://x.com",
        "itemKey": "ct0",
        "cache": false
      }
    ],
    "id": "x:following"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "User Tweets",
    "params": {
      "username": {
        "type": "text",
        "title": "Username",
        "default": "elonmusk"
      }
    },
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "slate",
    "type": "timeline",
    "category": "world",
    "home": "https://x.com",
    "secrets": [
      {
        "key": "csrfToken",
        "type": "cookie",
        "origin": "https://x.com",
        "itemKey": "ct0",
        "cache": false
      }
    ],
    "radar": [
      {
        "id": "x-user",
        "match": {
          "hosts": [
            "x.com",
            "twitter.com"
          ],
          "paths": [
            "/:username{/*rest}"
          ]
        },
        "title": {
          "type": "param",
          "name": "username",
          "transforms": [
            {
              "type": "prepend",
              "value": "@"
            }
          ]
        },
        "params": {
          "username": {
            "value": {
              "type": "path",
              "name": "username"
            },
            "pattern": "^\\w{1,15}$",
            "notIn": [
              "compose",
              "explore",
              "home",
              "i",
              "intent",
              "messages",
              "notifications",
              "search",
              "settings",
              "share"
            ]
          }
        },
        "confidence": 0.95
      }
    ],
    "id": "x:user"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/xueqiu.png",
    "providerTitle": "雪球",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://xueqiu.com",
    "id": "xueqiu:hot-stock"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/zaobao.png",
    "providerTitle": "联合早报",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "red",
    "type": "timeline",
    "category": "others",
    "home": "https://www.zaobao.com",
    "id": "zaobao:realtime"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/zhihu.png",
    "providerTitle": "知乎",
    "title": "全站热榜",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.zhihu.com",
    "id": "zhihu:hot-list"
  }
]
