// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "@newsnext/source-shared/typings"

export const sourceDescriptors: SourceDescriptor[] = [
  {
    "icon": "https://s3.newsnext.pro/icons/aihot.png",
    "providerTitle": "AIHot",
    "color": "blue",
    "type": "timeline",
    "category": "tech",
    "home": "https://aihot.virxact.com",
    "id": "aihot:all"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "热搜",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:hotword"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "热门视频",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:popular"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "排行榜",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:ranking"
  },
  {
    "icon": "https://www.google.com/chrome/static/images/favicons/favicon-96x96.png",
    "providerTitle": "Browser",
    "title": "History",
    "params": {
      "query": {
        "type": "text",
        "title": "Search",
        "default": ""
      },
      "dateRange": {
        "type": "select",
        "title": "Date range",
        "options": [
          {
            "label": "Today",
            "value": "today"
          },
          {
            "label": "Last 7 days",
            "value": "week"
          },
          {
            "label": "Last 30 days",
            "value": "month"
          },
          {
            "label": "All history",
            "value": "all"
          }
        ],
        "default": "week"
      },
      "maxResults": {
        "type": "number",
        "title": "Limit",
        "default": 50,
        "min": 1,
        "max": 100
      }
    },
    "color": "sky",
    "type": "timeline",
    "category": "others",
    "id": "browser:history"
  },
  {
    "icon": "https://www.google.com/chrome/static/images/favicons/favicon-96x96.png",
    "providerTitle": "Browser",
    "title": "Bookmarks",
    "params": {
      "folder": {
        "type": "text",
        "title": "Folder",
        "description": "Leave empty to include every bookmark. Use a folder ID, title, or path.",
        "default": ""
      },
      "maxResults": {
        "type": "number",
        "title": "Limit",
        "default": 50,
        "min": 1,
        "max": 200
      }
    },
    "color": "sky",
    "type": "timeline",
    "category": "others",
    "id": "browser:bookmarks"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "电报",
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn/telegraph",
    "id": "cls:telegraph"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "深度",
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn/depth",
    "id": "cls:depth"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "热门",
    "color": "red",
    "type": "hottest",
    "category": "finance",
    "home": "https://www.cls.cn",
    "id": "cls:hot-article"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/folo.png",
    "providerTitle": "Folo",
    "title": "Feed",
    "params": {
      "feedId": {
        "type": "text",
        "title": "Feed ID",
        "default": "71931642168770560"
      }
    },
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://folo.is",
    "id": "folo:feed"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/folo.png",
    "providerTitle": "Folo",
    "title": "List",
    "params": {
      "listId": {
        "type": "text",
        "title": "List ID",
        "default": "68649150114432000"
      }
    },
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://folo.is",
    "id": "folo:list"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/github.png",
    "providerTitle": "GitHub",
    "title": "Trending",
    "params": {
      "language": {
        "type": "text",
        "title": "Language",
        "description": "Programming language slug used by GitHub Trending, such as javascript, go, or rust.",
        "default": ""
      },
      "spokenLanguage": {
        "type": "text",
        "title": "Spoken Language",
        "description": "Repository description language code, such as en, zh, or ja.",
        "default": ""
      },
      "dateRange": {
        "type": "select",
        "title": "Date range",
        "options": [
          {
            "label": "Today",
            "value": "daily"
          },
          {
            "label": "This week",
            "value": "weekly"
          },
          {
            "label": "This month",
            "value": "monthly"
          }
        ],
        "default": "daily"
      }
    },
    "color": "slate",
    "type": "hottest",
    "category": "others",
    "home": "https://github.com/trending",
    "id": "github:trending"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Hottest",
    "color": "orange",
    "type": "hottest",
    "category": "others",
    "home": "https://news.ycombinator.com/",
    "id": "hackernews:top"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Newest",
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://news.ycombinator.com/newest",
    "id": "hackernews:newest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Show",
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/show",
    "id": "hackernews:show"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Ask",
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/ask",
    "id": "hackernews:ask"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/linuxdo.png",
    "providerTitle": "Linux.do",
    "title": "Latest",
    "color": "slate",
    "type": "timeline",
    "category": "tech",
    "home": "https://linux.do",
    "id": "linuxdo:latest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/linuxdo.png",
    "providerTitle": "Linux.do",
    "title": "Hot",
    "color": "slate",
    "type": "hottest",
    "category": "tech",
    "home": "https://linux.do",
    "id": "linuxdo:top-daily"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/netease-music.png",
    "providerTitle": "网易云音乐",
    "title": "飙升榜",
    "params": {
      "id": {
        "type": "text",
        "default": "19723756",
        "title": "Playlist"
      }
    },
    "color": "red",
    "type": "hottest",
    "category": "others",
    "home": "https://music.163.com/#/playlist?id=19723756",
    "id": "netease-music:playlist"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/newsnow.png",
    "providerTitle": "NEWS NOW",
    "params": {
      "locale": {
        "type": "select",
        "options": [
          {
            "label": "US",
            "value": "us"
          },
          {
            "label": "UK",
            "value": "uk"
          },
          {
            "label": "Nigeria",
            "value": "ng"
          },
          {
            "label": "România",
            "value": "ro"
          },
          {
            "label": "Italia",
            "value": "it"
          },
          {
            "label": "Canada",
            "value": "ca"
          },
          {
            "label": "Australia",
            "value": "au"
          }
        ],
        "default": "us",
        "title": "Locale"
      },
      "topic": {
        "type": "text",
        "default": "US",
        "title": "Topic"
      }
    },
    "color": "red",
    "type": "timeline",
    "category": "others",
    "home": "https://www.newsnow.com",
    "id": "newsnow:topic-latest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/tieba.png",
    "providerTitle": "百度贴吧",
    "title": "热议",
    "color": "blue",
    "type": "hottest",
    "category": "china",
    "home": "https://tieba.baidu.com",
    "id": "tieba:hot-topic"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/v2ex.png",
    "providerTitle": "V2EX",
    "params": {
      "feed": {
        "type": "select",
        "title": "Feed",
        "options": [
          {
            "label": "Create",
            "value": "create"
          },
          {
            "label": "Ideas",
            "value": "ideas"
          },
          {
            "label": "Programmer",
            "value": "programmer"
          },
          {
            "label": "Share",
            "value": "share"
          }
        ],
        "default": "ideas"
      }
    },
    "color": "slate",
    "category": "others",
    "home": "https://v2ex.com/",
    "id": "v2ex:feed"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/weibo.png",
    "providerTitle": "微博",
    "color": "red",
    "type": "hottest",
    "category": "others",
    "home": "https://s.weibo.com/top/summary?cate=realtimehot",
    "id": "weibo:hot-search"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "Trending",
    "params": {
      "location": {
        "type": "select",
        "title": "Location",
        "options": [
          {
            "label": "Worldwide",
            "value": "1"
          },
          {
            "label": "United States",
            "value": "23424977"
          },
          {
            "label": "United Kingdom",
            "value": "23424975"
          },
          {
            "label": "Japan",
            "value": "23424856"
          },
          {
            "label": "Hong Kong",
            "value": "24865698"
          },
          {
            "label": "Taiwan",
            "value": "23424971"
          },
          {
            "label": "Singapore",
            "value": "23424948"
          },
          {
            "label": "India",
            "value": "23424848"
          },
          {
            "label": "Brazil",
            "value": "23424768"
          },
          {
            "label": "Germany",
            "value": "23424829"
          }
        ],
        "default": "1"
      }
    },
    "color": "slate",
    "type": "hottest",
    "category": "world",
    "home": "https://x.com",
    "id": "x:place-trends"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "Recommended",
    "color": "slate",
    "type": "timeline",
    "category": "world",
    "home": "https://x.com",
    "id": "x:recommended"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "Following",
    "color": "slate",
    "type": "timeline",
    "category": "world",
    "home": "https://x.com",
    "id": "x:following"
  },
  {
    "icon": "https://x.com/favicon.ico",
    "providerTitle": "X",
    "title": "User Tweets",
    "params": {
      "username": {
        "type": "text",
        "title": "Username",
        "default": "elonmusk"
      }
    },
    "color": "slate",
    "type": "timeline",
    "category": "world",
    "home": "https://x.com",
    "id": "x:user"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/xueqiu.png",
    "providerTitle": "雪球",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://xueqiu.com",
    "id": "xueqiu:hot-stock"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/zaobao.png",
    "providerTitle": "联合早报",
    "color": "red",
    "type": "timeline",
    "category": "others",
    "home": "https://www.zaobao.com",
    "id": "zaobao:realtime"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/zhihu.png",
    "providerTitle": "知乎",
    "title": "全站热榜",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.zhihu.com",
    "id": "zhihu:hot-list"
  }
]
