import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { getFavicon } from "@newsnext/shared/utils"

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = __dirname

const sourceGlobs = [
  new Bun.Glob("src/lib/*.{ts,json}"),
  new Bun.Glob("src/lib/**/index.{ts,json}"),
]
const SRC_PREFIX_REGEX = /^src\//
const TS_EXTENSION_REGEX = /\.ts$/
const SOURCE_EXTENSION_REGEX = /\.(?:json|ts)$/
const TEST_FILE_REGEX = /\.(?:test|spec)\.ts$/

async function writeIfChanged(path: string, content: string): Promise<void> {
  const file = Bun.file(path)
  const currentContent = await file.exists() ? await file.text() : undefined
  if (currentContent !== content) {
    await file.write(content)
  }
}

async function generate(): Promise<void> {
  const files = new Set<string>()

  for (const glob of sourceGlobs) {
    for await (const file of glob.scan(rootDir)) {
      if (TEST_FILE_REGEX.test(file)) continue
      files.add(file)
    }
  }

  const sortedFiles = Array.from(files).sort()

  const importStatements: string[] = []
  const providerEntries: string[] = []
  const providerIds = new Set<string>()
  let hasJsonProvider = false

  sortedFiles.forEach((file, index) => {
    const sourcePath = file.replace(SRC_PREFIX_REGEX, "")
    const isJson = sourcePath.endsWith(".json")
    const importPath = `./${isJson ? sourcePath : sourcePath.replace(TS_EXTENSION_REGEX, "")}`

    const pathParts = sourcePath.replace(SOURCE_EXTENSION_REGEX, "").split("/")
    const key = pathParts[pathParts.length - 1] === "index"
      ? pathParts[pathParts.length - 2]
      : pathParts[pathParts.length - 1]
    if (providerIds.has(key)) {
      throw new Error(`Duplicate source provider ID "${key}"`)
    }
    providerIds.add(key)

    const alias = `provider_${index}`
    importStatements.push(
      isJson
        ? `import ${alias} from "${importPath}" with { type: "json" }`
        : `import ${alias} from "${importPath}"`,
    )
    providerEntries.push(
      `  ${JSON.stringify(key)}: resolveProvider(${JSON.stringify(key)}, ${alias}${isJson ? " as ProviderConfig" : ""})`,
    )
    hasJsonProvider ||= isJson
  })

  const indexContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts

${importStatements.join("\n")}
${hasJsonProvider ? "import type { ProviderConfig } from \"./utils/source\"\n" : ""}import { resolveProvider } from "./utils/source"

export const providers = {
${providerEntries.join(",\n")}
}
`

  const indexPath = join(rootDir, "src", "index.ts")
  await writeIfChanged(indexPath, indexContent)

  const { providers } = await import(`${indexPath}?updated=${Date.now()}`)
  console.log("Found providers:", Object.keys(providers))

  const sourceDescriptors = []
  for (const [provider, providerDefinition] of Object.entries(providers)) {
    for (const [sourceId, source] of Object.entries((providerDefinition as any).sources)) {
      const { loader, ...meta } = source as any
      const key = meta.key || sourceId
      const descriptor = { ...meta }
      delete descriptor.key
      sourceDescriptors.push({
        ...descriptor,
        icon: descriptor.icon ?? (descriptor.home ? getFavicon(descriptor.home) : undefined),
        id: `${provider}:${key}`,
      })
    }
  }

  const metadataContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "@newsnext/source/typings"

export const sourceDescriptors: SourceDescriptor[] = ${JSON.stringify(sourceDescriptors, null, 2)}
`

  await writeIfChanged(join(rootDir, "src", "metadata.ts"), metadataContent)
  console.log("Generated src/metadata.ts with", sourceDescriptors.length, "entries")
}

await generate()
