import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import jsonSources from "@newsnext/registry" with { type: "json" }
import { getFavicon } from "@newsnext/shared/utils"
import { resolveSourceRegistry } from "./src/utils/source"

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = __dirname

const sourceGlobs = [
  new Bun.Glob("src/lib/*.ts"),
  new Bun.Glob("src/lib/**/index.ts"),
]
const SRC_PREFIX_REGEX = /^src\//
const TS_EXTENSION_REGEX = /\.ts$/
const TEST_FILE_REGEX = /\.(?:test|spec)\.ts$/

async function writeIfChanged(path: string, content: string): Promise<void> {
  const file = Bun.file(path)
  const currentContent = await file.exists() ? await file.text() : undefined
  if (currentContent !== content) {
    await file.write(content)
  }
}

async function generate(): Promise<void> {
  const files = new Set<string>()

  for (const glob of sourceGlobs) {
    for await (const file of glob.scan(rootDir)) {
      if (TEST_FILE_REGEX.test(file)) continue
      files.add(file)
    }
  }

  const sortedFiles = Array.from(files).sort()

  const importStatements: string[] = []
  const providerEntries = new Map<string, string>()
  const providerIds = new Set<string>()

  sortedFiles.forEach((file, index) => {
    const sourcePath = file.replace(SRC_PREFIX_REGEX, "")
    const importPath = `./${sourcePath.replace(TS_EXTENSION_REGEX, "")}`

    const pathParts = sourcePath.replace(TS_EXTENSION_REGEX, "").split("/")
    const key = pathParts[pathParts.length - 1] === "index"
      ? pathParts[pathParts.length - 2]
      : pathParts[pathParts.length - 1]
    if (providerIds.has(key)) {
      throw new Error(`Duplicate source provider ID "${key}"`)
    }
    providerIds.add(key)

    const alias = `provider_${index}`
    importStatements.push(`import ${alias} from "${importPath}"`)
    providerEntries.set(
      key,
      `  ${JSON.stringify(key)}: resolveProvider(${JSON.stringify(key)}, ${alias})`,
    )
  })

  const indexContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts

${importStatements.join("\n")}
import { resolveProvider } from "./utils/source"

export const providers = {
${Array.from(providerEntries.entries())
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([, entry]) => entry)
  .join(",\n")}
}
`

  const indexPath = join(rootDir, "src", "index.ts")
  await writeIfChanged(indexPath, indexContent)

  const { providers } = await import(`${indexPath}?updated=${Date.now()}`)
  console.log("Found TypeScript providers:", Object.keys(providers))

  const runtimeJsonSources = resolveSourceRegistry(jsonSources)
  const runtimeTypescriptSources = Object.fromEntries(
    Object.entries(providers).flatMap(([providerId, providerDefinition]) =>
      Object.entries((providerDefinition as any).sources).map(([sourceId, source]) => [
        `${providerId}:${sourceId}`,
        source,
      ]),
    ),
  )
  for (const id of Object.keys(runtimeJsonSources)) {
    if (id in runtimeTypescriptSources) {
      throw new Error(`Duplicate source ID "${id}"`)
    }
  }
  const allSources = Object.fromEntries(
    Object.entries({
      ...runtimeTypescriptSources,
      ...runtimeJsonSources,
    }).sort(([left], [right]) => {
      const leftProvider = left.split(":")[0] ?? left
      const rightProvider = right.split(":")[0] ?? right
      return leftProvider.localeCompare(rightProvider)
    }),
  )
  const sourceDescriptors = []
  for (const [id, source] of Object.entries(allSources)) {
    const { loader, ...meta } = source as any
    const descriptor = { ...meta }
    delete descriptor.key
    sourceDescriptors.push({
      ...descriptor,
      icon: descriptor.icon ?? (descriptor.home ? getFavicon(descriptor.home) : undefined),
      id,
    })
  }

  const metadataContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "@newsnext/source/typings"

export const sourceDescriptors: SourceDescriptor[] = ${JSON.stringify(sourceDescriptors, null, 2)}
`

  await writeIfChanged(join(rootDir, "src", "metadata.ts"), metadataContent)
  console.log("Generated src/metadata.ts with", sourceDescriptors.length, "entries")
}

await generate()
