// Auto-generated file - do not edit manually
// This file is generated by build.ts

export const sources = {
  bilibili: (await import("./lib/bilibili")).default,
  github: (await import("./lib/github")).default,
  hackernews: (await import("./lib/hackernews")).default,
  html: (await import("./lib/html")).default,
  json: (await import("./lib/json")).default,
  newsnow: (await import("./lib/newsnow")).default,
  rss: (await import("./lib/rss")).default,
  rsshub: (await import("./lib/rsshub")).default,
  v2ex: (await import("./lib/v2ex")).default,
  weibo: (await import("./lib/weibo")).default,
  xueqiu: (await import("./lib/xueqiu")).default,
  zaobao: (await import("./lib/zaobao")).default,
}
