// Auto-generated file - do not edit manually
// This file is generated by build.ts

import source_0 from "./lib/bilibili"
import source_1 from "./lib/coolapk/index"
import source_2 from "./lib/github"
import source_3 from "./lib/hackernews"
import source_4 from "./lib/html"
import source_5 from "./lib/json"
import source_6 from "./lib/netease-music"
import source_7 from "./lib/newsnow"
import source_8 from "./lib/rss"
import source_9 from "./lib/rsshub"
import source_10 from "./lib/v2ex"
import source_11 from "./lib/weibo"
import source_12 from "./lib/xueqiu"
import source_13 from "./lib/zaobao"
import source_14 from "./lib/zhihu"

export const providers = {
  "bilibili": source_0,
  "coolapk": source_1,
  "github": source_2,
  "hackernews": source_3,
  "html": source_4,
  "json": source_5,
  "netease-music": source_6,
  "newsnow": source_7,
  "rss": source_8,
  "rsshub": source_9,
  "v2ex": source_10,
  "weibo": source_11,
  "xueqiu": source_12,
  "zaobao": source_13,
  "zhihu": source_14
}
