// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "./typings/sources"

export const sourceDescriptors: SourceDescriptor[] = [
  {
    "icon": "https://s3.newsnext.pro/icons/aihot.png",
    "providerTitle": "AIHot",
    "color": "blue",
    "type": "timeline",
    "category": "tech",
    "home": "https://aihot.virxact.com",
    "id": "aihot:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "热搜",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "热门视频",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:hot-video"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/bilibili.png",
    "providerTitle": "Bilibili",
    "title": "排行榜",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.bilibili.com",
    "id": "bilibili:ranking"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "电报",
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn/telegraph",
    "id": "cls:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "深度",
    "color": "red",
    "type": "timeline",
    "category": "finance",
    "home": "https://www.cls.cn/depth",
    "id": "cls:depth"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/cls.png",
    "providerTitle": "财联社",
    "title": "热门",
    "color": "red",
    "type": "hottest",
    "category": "finance",
    "home": "https://www.cls.cn",
    "id": "cls:hot"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/coolapk.png",
    "providerTitle": "CoolAPK",
    "title": "Today",
    "color": "green",
    "type": "hottest",
    "category": "others",
    "home": "https://coolapk.com",
    "id": "coolapk:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/folo.png",
    "providerTitle": "Folo",
    "title": "Feed",
    "params": {
      "feedId": {
        "type": "text",
        "title": "Feed ID",
        "default": "71931642168770560"
      }
    },
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://folo.is",
    "id": "folo:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/folo.png",
    "providerTitle": "Folo",
    "title": "List",
    "params": {
      "listId": {
        "type": "text",
        "title": "List ID",
        "default": "68649150114432000"
      }
    },
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://folo.is",
    "id": "folo:list"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/github.png",
    "providerTitle": "GitHub",
    "title": "Trending",
    "params": {
      "language": {
        "type": "text",
        "title": "Language",
        "description": "Programming language slug used by GitHub Trending, such as javascript, go, or rust.",
        "default": ""
      },
      "spokenLanguage": {
        "type": "text",
        "title": "Spoken Language",
        "description": "Repository description language code, such as en, zh, or ja.",
        "default": ""
      },
      "dateRange": {
        "type": "select",
        "title": "Date range",
        "options": [
          {
            "label": "Today",
            "value": "daily"
          },
          {
            "label": "This week",
            "value": "weekly"
          },
          {
            "label": "This month",
            "value": "monthly"
          }
        ],
        "default": "daily"
      }
    },
    "color": "slate",
    "type": "hottest",
    "category": "others",
    "home": "https://github.com/trending",
    "id": "github:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Hottest",
    "color": "orange",
    "type": "hottest",
    "category": "others",
    "home": "https://news.ycombinator.com/",
    "id": "hackernews:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Newest",
    "color": "orange",
    "type": "timeline",
    "category": "others",
    "home": "https://news.ycombinator.com/newest",
    "id": "hackernews:newest"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Show",
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/show",
    "id": "hackernews:show"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/hackernews.png",
    "providerTitle": "Hacker News",
    "title": "Ask",
    "color": "orange",
    "category": "others",
    "home": "https://news.ycombinator.com/ask",
    "id": "hackernews:ask"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/html.png",
    "providerTitle": "HTML Parser",
    "title": "36 氪",
    "params": {
      "url": {
        "type": "url",
        "default": "https://www.36kr.com/newsflashes",
        "title": "Target URL"
      },
      "decoding": {
        "type": "text",
        "default": "UTF-8",
        "title": "Decoding"
      },
      "items": {
        "type": "text",
        "default": ".newsflash-item",
        "title": "Items Selector"
      },
      "filter": {
        "type": "text",
        "default": "",
        "title": "Filter"
      },
      "titleSelector": {
        "type": "text",
        "default": "a.item-title",
        "title": "Title Selector"
      },
      "linkSelector": {
        "type": "text",
        "default": "a.item-title",
        "title": "Link Selector"
      }
    },
    "color": "orange",
    "category": "others",
    "home": "https://www.36kr.com/newsflashes",
    "id": "html:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/json.png",
    "providerTitle": "JSON",
    "title": "V2EX",
    "params": {
      "url": {
        "type": "url",
        "default": "https://www.v2ex.com/feed/ideas.json",
        "title": "Target URL"
      },
      "headers": {
        "type": "text",
        "default": "{}",
        "title": "Request Headers (JSON)"
      },
      "itemsPath": {
        "type": "text",
        "default": "items",
        "title": "Items Path"
      },
      "titlePath": {
        "type": "text",
        "default": "title",
        "title": "Title Path"
      },
      "urlPath": {
        "type": "text",
        "default": "url",
        "title": "URL Path"
      },
      "timestampPath": {
        "type": "text",
        "default": "date_published",
        "title": "Timestamp Path"
      }
    },
    "color": "cyan",
    "category": "others",
    "home": "https://www.json.org/",
    "id": "json:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/netease-music.png",
    "providerTitle": "网易云音乐",
    "title": "飙升榜",
    "params": {
      "id": {
        "type": "text",
        "default": "19723756",
        "title": "Playlist"
      }
    },
    "color": "red",
    "type": "hottest",
    "category": "others",
    "home": "https://music.163.com/#/playlist?id=19723756",
    "id": "netease-music:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/newsnow.png",
    "providerTitle": "NEWS NOW",
    "params": {
      "locale": {
        "type": "select",
        "options": [
          {
            "label": "US",
            "value": "us"
          },
          {
            "label": "UK",
            "value": "uk"
          },
          {
            "label": "Nigeria",
            "value": "ng"
          },
          {
            "label": "România",
            "value": "ro"
          },
          {
            "label": "Italia",
            "value": "it"
          },
          {
            "label": "Canada",
            "value": "ca"
          },
          {
            "label": "Australia",
            "value": "au"
          }
        ],
        "default": "us",
        "title": "Locale"
      },
      "topic": {
        "type": "text",
        "default": "US",
        "title": "Topic"
      }
    },
    "color": "red",
    "type": "timeline",
    "category": "others",
    "home": "https://www.newsnow.com",
    "id": "newsnow:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/rss.png",
    "providerTitle": "RSS",
    "title": "PCBeta",
    "params": {
      "url": {
        "type": "url",
        "default": "https://bbs.pcbeta.com/forum.php?mod=rss&fid=563&page=1",
        "title": "RSS URL"
      },
      "type": {
        "type": "select",
        "options": [
          {
            "label": "Hottest",
            "value": "hottest"
          },
          {
            "label": "Timeline",
            "value": "timeline"
          }
        ],
        "default": "timeline",
        "title": "Type"
      }
    },
    "color": "orange",
    "category": "others",
    "home": "https://rss.com/",
    "id": "rss:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/rsshub.png",
    "providerTitle": "RSSHub",
    "title": "36 氪",
    "params": {
      "route": {
        "type": "text",
        "default": "/36kr/newsflashes",
        "title": "Route"
      },
      "host": {
        "type": "url",
        "default": "https://rsshub.rssforever.com",
        "title": "Host"
      },
      "type": {
        "type": "select",
        "options": [
          {
            "label": "Hottest",
            "value": "hottest"
          },
          {
            "label": "Timeline",
            "value": "timeline"
          }
        ],
        "default": "timeline",
        "title": "Type"
      }
    },
    "color": "orange",
    "category": "others",
    "home": "https://rsshub.app/",
    "id": "rsshub:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/tieba.png",
    "providerTitle": "百度贴吧",
    "title": "热议",
    "color": "blue",
    "type": "hottest",
    "category": "china",
    "home": "https://tieba.baidu.com",
    "id": "tieba:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/v2ex.png",
    "providerTitle": "V2EX",
    "params": {
      "feeds": {
        "type": "multiselect",
        "title": "Feeds",
        "options": [
          {
            "label": "Create",
            "value": "create"
          },
          {
            "label": "Ideas",
            "value": "ideas"
          },
          {
            "label": "Programmer",
            "value": "programmer"
          },
          {
            "label": "Share",
            "value": "share"
          }
        ],
        "default": [
          "create",
          "ideas",
          "programmer",
          "share"
        ]
      }
    },
    "color": "slate",
    "category": "others",
    "home": "https://v2ex.com/",
    "id": "v2ex:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/weibo.png",
    "providerTitle": "微博",
    "color": "red",
    "type": "hottest",
    "category": "others",
    "home": "https://s.weibo.com/top/summary?cate=realtimehot",
    "id": "weibo:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/xueqiu.png",
    "providerTitle": "雪球",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://xueqiu.com",
    "id": "xueqiu:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/zaobao.png",
    "providerTitle": "联合早报",
    "color": "red",
    "type": "timeline",
    "category": "others",
    "home": "https://www.zaobao.com",
    "id": "zaobao:default"
  },
  {
    "icon": "https://s3.newsnext.pro/icons/zhihu.png",
    "providerTitle": "知乎",
    "title": "全站热榜",
    "color": "blue",
    "type": "hottest",
    "category": "others",
    "home": "https://www.zhihu.com",
    "id": "zhihu:default"
  }
]
