// Auto-generated file - do not edit manually
// This file is generated by build.ts

import provider_0 from "./lib/coolapk/index"

export const providers = {
  [provider_0.id ?? "coolapk"]: provider_0
}
