// Vendors the compiled SDK as a single-file bundle for `newsnext eval`.
// Runs as part of `bun --filter=@newsnext/sdk run build`. Skips silently
// when the sibling CLI checkout is absent (standalone web checkouts).
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const sdk = join(here, "..")
const distEntry = join(sdk, "dist", "index.js")
const cliVendor = join(sdk, "..", "..", "..", "cli", "vendor")

if (!existsSync(join(cliVendor, "..", "Cargo.toml"))) {
  console.log("No sibling CLI checkout; skipping SDK vendor bundle")
  process.exit(0)
}

if (!existsSync(distEntry)) {
  throw new Error(`Missing SDK dist: ${distEntry}. Run tsdown first.`)
}
const built = await Bun.build({ entrypoints: [distEntry], format: "esm", target: "node" })
if (!built.success) {
  throw new Error(`SDK bundle failed: ${built.logs.join("\n")}`)
}
const bundled = (await built.outputs[0]!.text())
  // Bun annotates bundled chunks with cwd-relative source paths, which differ
  // by invocation directory. Normalize them so the vendored file is stable.
  .split("\n")
  .map(line => /^\s*\/\/\s*\S*dist\/\S+\.js\s*$/.test(line) ? "// <sdk-chunk>" : line)
  .join("\n")
mkdirSync(cliVendor, { recursive: true })
const header = [
  "// Generated bundle of @newsnext/sdk for `newsnext eval`. Do not edit.",
  "// Regenerated by `bun --filter=@newsnext/sdk run build`.",
  "",
].join("\n")
const target = join(cliVendor, "newsnext-sdk.js")
rmSync(target, { force: true })
writeFileSync(target, header + bundled)
console.log(`Vendored SDK bundle to ${target}`)
