/* eslint-disable */
// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceDescriptor } from "@newsnext/source-shared/typings"

export const sourceDescriptors: SourceDescriptor[] = [
  {
    "icon": "https://s3.newsnext.pro/icons/coolapk.png",
    "providerTitle": "CoolAPK",
    "title": "Today",
    "paramsSchemaVersion": 1,
    "cacheVersion": 1,
    "color": "green",
    "type": "hottest",
    "category": "others",
    "home": "https://coolapk.com",
    "id": "coolapk:default"
  }
]
