// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionStatus } from "./CollectionStatus.js";
import type { CommandResult } from "./CommandResult.js";
import type { ExtensionCommand } from "./ExtensionCommand.js";
import type { LogEntry } from "./LogEntry.js";
import type { OfflineWorker } from "./OfflineWorker.js";
import type { Workspace } from "./Workspace.js";
import type { WorkspacePatch } from "./WorkspacePatch.js";

export type HostToExtension = { "type": "sdkFrame", requestId: string, frame: unknown, } | { "type": "chunk", transferId: string, index: number, total: number, data: string, } | { "type": "ready", protocolVersion: number, daemonVersion: string, capabilities?: Array<string>, widgetServerUrl: string, workspace: Workspace, localInstanceIds: Array<string>, workerRoutingRevision: number, offlineWorkers: Array<OfflineWorker>, } | { "type": "workerRoutingChanged", revision: number, localInstanceIds: Array<string>, offlineWorkers: Array<OfflineWorker>, } | { "type": "execute", request: ExtensionCommand, } | { "type": "error", requestId: string | null, code?: string, message: string, } | { "type": "widgetSnapshotResult", requestId: string, result: CommandResult, } | { "type": "workspaceChanged", patch: WorkspacePatch, localInstanceIds: Array<string>, } | { "type": "workspaceResult", requestId: string, revision: number, localInstanceIds: Array<string>, } | { "type": "instanceResult", requestId: string, result: CommandResult, } | { "type": "collectionStatusChanged", status: CollectionStatus, } | { "type": "collectionStatusResult", requestId: string, status: CollectionStatus, } | { "type": "logsResult", requestId: string, logs: Array<LogEntry>, } | { "type": "workerTakeoverResult", requestId: string, };
