// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One renderable Insight definition.
 *
 * `view` and `params` stay untyped here: the daemon owns the Insight manifest schema and the
 * extension validates both before rendering them. Custom views omit `view` and use `url`.
 */
export type InsightCatalogEntry = { id: string, title: string, color: string, width: number, height: number, minWidth: number, minHeight: number,
/**
 * Entry document for a custom view, served by the loopback Insight server.
 */
url?: string, view?: unknown, params: unknown, dataRevision: string, dataFiles: Array<string>,
/**
 * Fingerprint of the rendered view: the custom entry document bytes, or the
 * built-in view definition. The host reloads the view when it changes.
 */
viewRevision: string,
/**
 * False when the Insight declares no queries and no data.mjs; the host hides refresh.
 */
hasData: boolean, refreshIntervalMs: number, };
