// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NowLayerSort } from "./NowLayerSort.js";

export type NowLayer = { sort: NowLayerSort, };
