// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One renderable Widget definition.
 *
 * `view` and `params` stay untyped here: the daemon owns the Widget manifest schema and the
 * extension validates both before rendering them.
 */
export type WidgetCatalogEntry = { id: string, title: string, color: string, width: number, height: number, minWidth: number, minHeight: number, 
/**
 * Entry document for a custom view, served by the loopback Widget server.
 */
url?: string, view: unknown, params: unknown, dataRevision: string, dataFiles: Array<string>, refreshIntervalMs: number, };
