// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardLayer } from "./BoardLayer.js";
import type { NextLayer } from "./NextLayer.js";
import type { NowLayer } from "./NowLayer.js";

export type WorkspaceBoard = { color: string, createdAt: number, defaultLayer: BoardLayer, id: string, instanceIds: Array<string>, name: string, nowLayer: NowLayer, nextLayer: NextLayer, };
