import { COLORS } from "@newsnext/shared/constants"

function generateCss() {
  const colorsList = COLORS.join(",")
  return [
    `@source inline("bg-{${colorsList}}-{300,400}/{10,35,40,60}")`,
    `@source inline("sprinkle-{${colorsList}}-400")`,
    `@source inline("text-{${colorsList}}-400")`,
  ].join(";\n")
}

try {
  const cssContent = generateCss()
  console.log("/* auto generated by bun run tw:safelist */\n")
  console.log(cssContent)
} catch (error) {
  console.error("Error generating safelist:", error)
  process.exit(1)
}
