import { COLORS } from "@newsnext/shared/constants"

const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

const DEFAULT_THEME_COLOR = "red"

function generateCss() {
  let css = "@theme {\n"

  // Generate default theme (red)
  SHADES.forEach((shade) => {
    css += `    --color-theme-${shade}: var(--color-${DEFAULT_THEME_COLOR}-${shade});\n`
  })

  css += "}\n\n"
  css += "@layer theme {\n"

  // Generate other color classes
  COLORS.forEach((color) => {
    css += `  .${color} {\n`
    SHADES.forEach((shade) => {
      css += `    --color-theme-${shade}: var(--color-${color}-${shade});\n`
    })
    css += "  }\n"
  })

  css += "}\n"

  return css
}

try {
  const cssContent = generateCss()
  console.log("/* auto generated by bun run tw:themes */\n")
  console.log(cssContent)
} catch (error) {
  console.error("Error generating themes:", error)
  process.exit(1)
}
