import type {
  ExecutableSourceLoaders,
  ProviderConfig,
  SourceRegistryConfig,
} from "@newsnext/source/registry"
import { basename, dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import {
  flattenProviderConfig,
  resolveProvider,
  resolveSourceRegistry,
} from "@newsnext/source/registry"

const rootDir = dirname(fileURLToPath(import.meta.url))
const jsonProviderGlob = new Bun.Glob("src/*.json")
const typescriptProviderGlobs = [
  new Bun.Glob("src/*.ts"),
  new Bun.Glob("src/**/index.ts"),
]
const SRC_PREFIX_REGEX = /^src\//
const TS_EXTENSION_REGEX = /\.ts$/
const TEST_FILE_REGEX = /\.(?:test|spec)\.ts$/

async function writeIfChanged(path: string, content: string): Promise<void> {
  const file = Bun.file(path)
  const currentContent = await file.exists() ? await file.text() : undefined
  if (currentContent !== content) {
    await file.write(content)
  }
}

async function generate(): Promise<void> {
  const typescriptProviderFiles = new Set<string>()
  for (const glob of typescriptProviderGlobs) {
    for await (const file of glob.scan(rootDir)) {
      if (!TEST_FILE_REGEX.test(file)) {
        typescriptProviderFiles.add(file)
      }
    }
  }

  const importStatements: string[] = []
  const providerEntries = new Map<string, string>()
  for (const [index, file] of Array.from(typescriptProviderFiles).sort().entries()) {
    const sourcePath = file.replace(SRC_PREFIX_REGEX, "")
    const importPath = `./src/${sourcePath.replace(TS_EXTENSION_REGEX, "")}`
    const pathParts = sourcePath.replace(TS_EXTENSION_REGEX, "").split("/")
    const providerId = pathParts.at(-1) === "index"
      ? pathParts.at(-2)
      : pathParts.at(-1)

    if (!providerId || providerEntries.has(providerId)) {
      throw new Error(`Duplicate executable provider ID "${providerId ?? ""}"`)
    }

    const alias = `provider_${index}`
    importStatements.push(`import ${alias} from "${importPath}"`)
    providerEntries.set(providerId, `  ${JSON.stringify(providerId)}: ${alias}`)
  }

  const loadersPath = join(rootDir, "loaders.ts")
  await writeIfChanged(
    loadersPath,
    `// Auto-generated file - do not edit manually
// This file is generated by build.ts

import type { RuntimeSource } from "@newsnext/source/types"
import type {
  ExecutableSourceLoaders,
  ProviderConfig,
} from "@newsnext/source/registry"
import {
  resolveProvider,
  resolveSourceRegistry,
} from "@newsnext/source/registry"
${importStatements.join("\n")}

const providerConfigs: Record<string, ProviderConfig> = {
${Array.from(providerEntries.values()).join(",\n")}
}

export const executableLoaders: ExecutableSourceLoaders = Object.fromEntries(
  Object.entries(providerConfigs).flatMap(([providerId, providerConfig]) => {
    const provider = resolveProvider(providerId, providerConfig)
    return Object.entries(provider.sources).map(
      ([sourceId, source]) => [\`\${providerId}:\${sourceId}\`, source.loader],
    )
  }),
)

export function resolveSources(registry: unknown): Record<string, RuntimeSource> {
  return resolveSourceRegistry(registry, executableLoaders)
}
`,
  )

  const generated = await import(`${loadersPath}?updated=${Date.now()}`) as {
    executableLoaders: ExecutableSourceLoaders
  }

  const registry: Record<string, SourceRegistryConfig> = {}
  function addSource(id: string, source: SourceRegistryConfig): void {
    if (id in registry) {
      throw new Error(`Duplicate source ID "${id}"`)
    }
    registry[id] = source
  }

  const jsonProviderFiles: string[] = []
  for await (const file of jsonProviderGlob.scan(rootDir)) {
    jsonProviderFiles.push(file)
  }
  for (const file of jsonProviderFiles.sort()) {
    const providerId = basename(file, ".json")
    const provider = await Bun.file(join(rootDir, file)).json() as ProviderConfig
    for (const [id, source] of Object.entries(flattenProviderConfig(providerId, provider))) {
      addSource(id, source)
    }
  }

  for (const file of Array.from(typescriptProviderFiles).sort()) {
    const sourcePath = file.replace(SRC_PREFIX_REGEX, "")
    const pathParts = sourcePath.replace(TS_EXTENSION_REGEX, "").split("/")
    const providerId = pathParts.at(-1) === "index"
      ? pathParts.at(-2)
      : pathParts.at(-1)
    if (!providerId) {
      throw new Error(`Cannot determine provider ID for "${file}"`)
    }

    const module = await import(`${join(rootDir, file)}?registry=${Date.now()}`) as {
      default: ProviderConfig
    }
    const resolvedProvider = resolveProvider(providerId, module.default)
    for (const [id, source] of Object.entries(flattenProviderConfig(providerId, module.default))) {
      const { loader: _loader, ...config } = source
      const sourceId = id.slice(providerId.length + 1)
      const resolvedSource = resolvedProvider.sources[sourceId]
      if (!resolvedSource) {
        throw new Error(`Executable source "${id}" was not resolved`)
      }
      addSource(id, {
        ...config,
        capabilities: resolvedSource.capabilities,
      })
    }
  }

  const sortedRegistry = Object.fromEntries(
    Object.entries(registry).sort(([left], [right]) => left.localeCompare(right)),
  )
  resolveSourceRegistry(sortedRegistry, generated.executableLoaders)

  await writeIfChanged(
    join(rootDir, "registry.json"),
    `${JSON.stringify(sortedRegistry, null, 2)}\n`,
  )
  console.log(`Generated registry.json with ${Object.keys(sortedRegistry).length} sources`)
  console.log(
    `Generated loaders.ts with ${Object.keys(generated.executableLoaders).length} executable loaders`,
  )
}

await generate()
