// Auto-generated file - do not edit manually
// This file is generated by build.ts

import type { RuntimeSource } from "@newsnext/source/types"
import type {
  ExecutableSourceLoaders,
  ProviderConfig,
} from "@newsnext/source/registry"
import {
  resolveProvider,
  resolveSourceRegistry,
} from "@newsnext/source/registry"
import provider_0 from "./src/bilibili"
import provider_1 from "./src/browser"
import provider_2 from "./src/cls"
import provider_3 from "./src/folo"
import provider_4 from "./src/jike/index"
import provider_5 from "./src/reddit/index"
import provider_6 from "./src/weibo/index"
import provider_7 from "./src/x/index"

const providerConfigs: Record<string, ProviderConfig> = {
  "bilibili": provider_0,
  "browser": provider_1,
  "cls": provider_2,
  "folo": provider_3,
  "jike": provider_4,
  "reddit": provider_5,
  "weibo": provider_6,
  "x": provider_7
}

export const executableLoaders: ExecutableSourceLoaders = Object.fromEntries(
  Object.entries(providerConfigs).flatMap(([providerId, providerConfig]) => {
    const provider = resolveProvider(providerId, providerConfig)
    return Object.entries(provider.sources).map(
      ([sourceId, source]) => [`${providerId}:${sourceId}`, source.loader],
    )
  }),
)

export function resolveSources(registry: unknown): Record<string, RuntimeSource> {
  return resolveSourceRegistry(registry, executableLoaders)
}
