import { join } from "node:path"
import { Glob } from "bun"
import { build } from "tsdown"

const glob = new Glob("./src/core/*.ts")
const deepIndexGlob = new Glob("./src/core/**/index.ts")

const files = new Set<string>()

for await (const file of glob.scan(".")) {
  files.add(file)
}

for await (const file of deepIndexGlob.scan(".")) {
  files.add(file)
}

// Sort files for consistent output
const sortedFiles = Array.from(files).sort()

// Generate import statements using dynamic import() as object properties
const imports = sortedFiles.map((file) => {
  // Remove ./src/ prefix and .ts extension, convert to relative import path
  // Since index.ts is in src/, we need relative paths from src/
  const importPath = file.replace(/^\.\/src\//, "./").replace(/\.ts$/, "")

  // Extract key name from path
  // e.g., "./core/coolapk/index" -> "coolapk"
  // e.g., "./core/github" -> "github"
  const pathParts = importPath.split("/")
  const key = pathParts[pathParts.length - 1] === "index"
    ? pathParts[pathParts.length - 2]
    : pathParts[pathParts.length - 1]

  return `  ${key}: (await import("${importPath}")).default`
})

const indexContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts

export const sources = {
${imports.join(",\n")}
}
`

const indexPath = join(process.cwd(), "src", "index.ts")
await Bun.file(indexPath).write(indexContent)

const { sources } = await import(indexPath)
console.log(sources)

await build({
  entry: indexPath,
  outDir: join(process.cwd(), "dist"),
  dts: true,
})