import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
// import { build } from "tsdown"

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = __dirname

const glob = new Bun.Glob("src/lib/*.ts")
const deepIndexGlob = new Bun.Glob("src/lib/**/index.ts")

const files = new Set<string>()

for await (const file of glob.scan(rootDir)) {
  files.add(file)
}

for await (const file of deepIndexGlob.scan(rootDir)) {
  files.add(file)
}

// Sort files for consistent output
const sortedFiles = Array.from(files).sort()

// Generate import statements and entries
const importStatements: string[] = []
const indexEntries: string[] = []
const sourceKeys: string[] = []

sortedFiles.forEach((file, index) => {
  // Remove src/ prefix and .ts extension, convert to relative import path
  const importPath = `./${file.replace(/^src\//, "").replace(/\.ts$/, "")}`

  // Extract key name from path
  const pathParts = importPath.split("/")
  const key = pathParts[pathParts.length - 1] === "index"
    ? pathParts[pathParts.length - 2]
    : pathParts[pathParts.length - 1]

  const alias = `source_${index}`
  importStatements.push(`import ${alias} from "${importPath}"`)
  indexEntries.push(`  ${JSON.stringify(key)}: ${alias}`)
  sourceKeys.push(key)
})

const indexContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts

${importStatements.join("\n")}

export const sources = {
${indexEntries.join(",\n")}
}
`

const indexPath = join(rootDir, "src", "index.ts")
await Bun.file(indexPath).write(indexContent)

// Dynamic import might fail if the file hasn't been written to disk yet or module cache
// Just log the keys we found
console.log("Found sources:", sourceKeys)

// Generate metadata.ts
const { sources } = await import(indexPath)

const metadata = []
for (const [namespace, variants] of Object.entries(sources)) {
  for (const [variantId, variant] of Object.entries(variants as any)) {
    const { fetcher, ...meta } = variant as any
    metadata.push({
      ...meta,
      id: meta.id || variantId,
      namespace,
    })
  }
}

const metadataContent = `// Auto-generated file - do not edit manually
// This file is generated by build.ts
import type { SourceMeta } from "./typings/sources"

export const metadata: SourceMeta[] = ${JSON.stringify(metadata, null, 2)}
`

await Bun.file(join(rootDir, "src", "metadata.ts")).write(metadataContent)
console.log("Generated src/metadata.ts with", metadata.length, "entries")

// await build({
//   entry: indexPath,
//   outDir: join(rootDir, "dist"),
//   dts: true,
// })
